"""The model-chair framework: exact named identities, verification, and receipts."""

from .config import load_models_toml, parse_models_config
from .errors import (
    ALL_REFUSAL_TYPES,
    AdapterFetchRefusal,
    CacheRevisionRefusal,
    ChairRefusal,
    ConfigurationRefusal,
    DigestMismatchRefusal,
    LocalPathRefusal,
    ProtocolClauseRefusal,
    ReceiptRefusal,
    ServingRecipeRefusal,
    UnresolvedChairRefusal,
    is_closed_refusal,
)
from .manifests import (
    build_manifest,
    manifest_digest,
    read_manifest,
    verify_snapshot,
    write_manifest,
)
from .models import (
    AbsentChair,
    ChairIdentity,
    DigestManifest,
    ManifestRow,
    ModelsConfig,
    ServingDetails,
    ServingReceipt,
    VerifiedSnapshot,
    WitnessFloorStatus,
    is_hf_revision,
    is_sha256,
)
from .protocol import ChairProtocol, exercise_contract
from .receipts import RECEIPT_SCHEMA, build_receipt, receipt_record, validate_receipt
from .registry import (
    CACHE_DESCRIPTOR,
    ChairRegistry,
    HuggingFaceFetcher,
    SnapshotFetcher,
    resolve_local_path,
)

__all__ = [
    "ALL_REFUSAL_TYPES",
    "CACHE_DESCRIPTOR",
    "AbsentChair",
    "AdapterFetchRefusal",
    "CacheRevisionRefusal",
    "ConfigurationRefusal",
    "DigestManifest",
    "DigestMismatchRefusal",
    "HuggingFaceFetcher",
    "LocalPathRefusal",
    "ManifestRow",
    "ModelsConfig",
    "ProtocolClauseRefusal",
    "RECEIPT_SCHEMA",
    "ReceiptRefusal",
    "ChairIdentity",
    "ChairProtocol",
    "ChairRefusal",
    "ChairRegistry",
    "ServingDetails",
    "ServingReceipt",
    "ServingRecipeRefusal",
    "SnapshotFetcher",
    "UnresolvedChairRefusal",
    "VerifiedSnapshot",
    "WitnessFloorStatus",
    "build_manifest",
    "build_receipt",
    "exercise_contract",
    "is_closed_refusal",
    "is_hf_revision",
    "is_sha256",
    "load_models_toml",
    "manifest_digest",
    "parse_models_config",
    "read_manifest",
    "receipt_record",
    "resolve_local_path",
    "validate_receipt",
    "verify_snapshot",
    "write_manifest",
]
