"""Render the declared proof pages and write both declarations that describe them.

Run from the repository root:

    python3 proof/build_fixture.py

It writes three things and nothing else:

  proof/fixtures/<fixture-id>/page-N.png   the checked-in bytes themselves
  proof/fixtures.toml                      the ingress declaration the hook enforces
  proof/skeleton_fixture.toml              the pipeline's declaration of what is on them

The checked-in bytes are the authority, not this script: zlib output can differ
between builds, so regenerated bytes may differ while decoding to the same pixels,
which is what the test beside this script checks.

`fixtures.toml` says which bytes may enter git (the ingress hook enforces it);
`skeleton_fixture.toml` says what is on the pages, and the stages read it as data.
"""

import json
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from common.imaging import crop_png  # noqa: E402
from proof.synthetic_pages import ALL_PAGES, FIXTURE_ID, render_page  # noqa: E402

PROOF_ROOT = Path(__file__).resolve().parent
FIXTURE_DIR = PROOF_ROOT / "fixtures" / FIXTURE_ID
_BARE_TOML_KEY = re.compile(r"^[A-Za-z0-9_-]+$")

# What the fake Perlector establishes for each act. It proves wiring only, never
# reading ink.
ACTS = (
    {
        "key": "a1",
        "page_ordinal": 1,
        "proposal_ordinal": 0,
        "text": "SYNTHETIC ACT ONE alpha beta gamma",
    },
    {
        "key": "a2",
        "page_ordinal": 1,
        "proposal_ordinal": 1,
        "text": "SYNTHETIC ACT TWO delta epsilon zeta eta",
    },
)

# Chair 1 agrees, chair 2 differs in one token and chair 3 stops short, so the
# dissent record's shape is exercised. Dissent is not a quality signal.
TESTIMONY = {
    "a1": {
        "attestator_1": "SYNTHETIC ACT ONE alpha beta gamma",
        "attestator_2": "SYNTHETIC ACT ONE alpha beta gamna",
        "attestator_3": "SYNTHETIC ACT ONE alpha beta",
    },
    "a2": {
        "attestator_1": "SYNTHETIC ACT TWO delta epsilon zeta eta",
        "attestator_2": "SYNTHETIC ACT TWO delta epsilon zeta",
        "attestator_3": "SYNTHETIC ACT TWO delta epsiIon zeta eta",
    },
}


def chandra_raw_response_for_act(payload: str, act_key: str) -> str:
    """Bind fixture text to native geometry over its declared act.

    Scenario overrides must retain both facts; text without reported geometry
    leaves a page witness unable to attach to the act it read.
    """
    act = next(row for row in ACTS if row["key"] == act_key)
    page = next(row for row in ALL_PAGES if row["ordinal"] == act["page_ordinal"])
    bounds = next(
        row["bounds"] for row in page["acts"] if row["ordinal"] == act["proposal_ordinal"]
    )
    return json.dumps(
        {
            "schema": "fixture-chandra-response.v1",
            "markdown": payload,
            "blocks": [
                {
                    "bbox": [
                        bounds["x"] + 0.25,
                        bounds["y"] + 0.5,
                        bounds["x"] + bounds["w"],
                        bounds["y"] + bounds["h"] + 0.1,
                    ]
                }
            ],
        },
        separators=(",", ":"),
    )


# Declared page geometry. It is deterministic stimulus for an unmeasured
# positive-area rule, not a calibrated threshold or an act assignment.
NATIVE_OBSERVATIONS = (
    # attestator_1 (Chandra) derives geometry from its native responses, so a box
    # here would double-count. attestator_3's box contains both proposals.
    # No live Churro response can produce this box: its format has no coordinates.
    # The fixture publishes it as native anyway; proof/test_fixture_declaration_contract.py
    # pins this row as the one whose chair cannot express layout.
    {"chair": "attestator_3", "page_ordinal": 1, "x": 12, "y": 15, "w": 188, "h": 223},
)

# Declared digests (all zeros) that cannot match the checked-in bytes, so the
# door refuses the page through its real inspection path, not a scenario branch.
PAGE_REFUSALS = (
    {"scenario": "refused-page", "ordinal": 2},
    {"scenario": "refused-first-page", "ordinal": 1},
)
_UNMATCHABLE_SHA256 = "0" * 64

# A recorded structure failure (there is no live structure model to fail). The
# page and every act on it must be held visibly, never skipped.
STRUCTURE_FAILURES = (
    {
        "scenario": "structure-failure",
        "page_ordinal": 1,
        "reason_code": "recorded-fixture-structure-failure",
    },
)


def _page_entry(n, act_key, cites, *, text=None, from_previous=False, to_next=False, kind="act"):
    return {
        "n": n,
        "kind": kind,
        "label": f"synthetic act {act_key}",
        "cites": cites,
        "text": TESTIMONY[act_key]["attestator_1"] if text is None else text,
        "continues_from_previous_page": from_previous,
        "continues_to_next_page": to_next,
    }


# What the fake Perlector answers when it reads a page whole (`reading_unit =
# "page"`). The ids are the page feed's: A is attestator_1 (Chandra, one boxed
# unit per declared act on page 1, one unboxed unit of page text on page 2), B
# is attestator_2 (DAI, one boxed unit per detector record), C is attestator_3
# (Churro, one unit per line, no boxes), L are Surya's lines.
# `happy` places every entry: page 1's by Chandra's boxes, page 2's by the
# Surya lines over a2's continuation. `page-review` reads page 1 the same way
# but cites no boxed id on page 2, so that entry is unplaced, DAI's record there
# goes unread, and the page accounting holds it (rules b, c, d, f, g and i).
# `page-no-act` reads page 1 as `happy` and page 2's one entry, placed as in
# `happy`, as `other`: a page the reading says holds no act, and on which the
# record detector finds nothing below its cap, so DAI saw nothing there. `page-other`
# reads a1 as `other`: the detector finds no record over a1, so DAI's one
# record on page 1 is a2's (B1), and no record lies in the `other` reading.
# Proves wiring only, never reading ink.
_PAGE_ONE_ANSWER = {
    "acts": [
        _page_entry(
            1, "a1", ["A1", "B1", "C1"], text="SYNTHETIC ACT ONE alpha beta [[gamma|gamna]]"
        ),
        _page_entry(2, "a2", ["A2", "B2", "C2"], to_next=True),
    ],
    "set_aside": [],
}
PAGE_ANSWERS = (
    {"scenario": "happy", "page_ordinal": 1, "answer": _PAGE_ONE_ANSWER},
    {
        "scenario": "happy",
        "page_ordinal": 2,
        "answer": {
            "acts": [_page_entry(1, "a2", ["A1", "B1", "C1", "L1-L3"], from_previous=True)],
            "set_aside": [],
        },
    },
    {"scenario": "page-review", "page_ordinal": 1, "answer": _PAGE_ONE_ANSWER},
    {
        "scenario": "page-review",
        "page_ordinal": 2,
        "answer": {
            "acts": [_page_entry(1, "a2", ["A1", "C1"], from_previous=True)],
            "set_aside": [],
        },
    },
    {"scenario": "page-no-act", "page_ordinal": 1, "answer": _PAGE_ONE_ANSWER},
    {
        "scenario": "page-no-act",
        "page_ordinal": 2,
        "answer": {
            "acts": [_page_entry(1, "a2", ["A1", "C1", "L1-L3"], from_previous=True, kind="other")],
            "set_aside": [],
        },
    },
    {
        "scenario": "page-other",
        "page_ordinal": 1,
        "answer": {
            "acts": [
                _page_entry(
                    1,
                    "a1",
                    ["A1", "C1"],
                    text="SYNTHETIC ACT ONE alpha beta [[gamma|gamna]]",
                    kind="other",
                ),
                _page_entry(2, "a2", ["A2", "B1", "C2"], to_next=True),
            ],
            "set_aside": [],
        },
    },
    {
        "scenario": "page-other",
        "page_ordinal": 2,
        "answer": {
            "acts": [_page_entry(1, "a2", ["A1", "B1", "C1", "L1-L3"], from_previous=True)],
            "set_aside": [],
        },
    },
)


def _with_entry(answer: dict, n: int, **fields) -> dict:
    """`answer` with entry `n`'s fields changed."""
    return {
        **answer,
        "acts": [{**entry, **fields} if entry["n"] == n else entry for entry in answer["acts"]],
    }


_HAPPY_PAGE_TWO_IDS = ("A1", "B1", "C1", "L1", "L2", "L3", "S1")


def _unbroken(pages: dict[int, Any] | None = None) -> dict[int, Any]:
    return {
        1: lambda answer: _with_entry(answer, 2, continues_to_next_page=False),
        2: lambda answer: _with_entry(answer, 1, continues_from_previous_page=False),
        **(pages or {}),
    }


# Scenarios whose reader answers as a base scenario's reader did, except on the
# pages named. Each maps its name to the base and, per page, what the answer
# becomes: a new answer from the base's, or reply text that is not an answer at
# all. The witness scenarios read `happy`'s answers, citing no Churro unit on a
# page where Churro returned none.
# `page-unread`: page 2's reply is not JSON, so the page is read as nothing
# while page 1's last act still says it runs on. `page-blank`: page 2 read as
# blank paper, every id on it set aside, with no act running onto it.
# `page-review-other`: page-review's unplaced entry read as `other`, with no
# act running onto it. `page-unbroken`, `page-other-unbroken` and
# `page-no-act-unbroken`: their base with no act running across the page
# break. `page-flags-disagree`: page 1's last act says it runs on and page 2's
# first says it does not. `page-runs-past-end`: nothing runs across the break,
# but page 2's act says it runs on past the run's last page.
def _citing_no_churro_unit(answer: dict) -> dict:
    """`answer` with every Churro (`C`) id dropped from its citations."""
    return {
        **answer,
        "acts": [
            {**entry, "cites": [cite for cite in entry["cites"] if not cite.startswith("C")]}
            for entry in answer["acts"]
        ],
    }


PAGE_ANSWER_VARIANTS = {
    "page-unread": ("happy", {2: "the reply is not JSON"}),
    "page-blank": (
        "happy",
        {
            1: lambda answer: _with_entry(answer, 2, continues_to_next_page=False),
            2: lambda _answer: {
                "acts": [],
                "set_aside": [
                    {"id": identifier, "reason": "blank paper"}
                    for identifier in _HAPPY_PAGE_TWO_IDS
                ],
            },
        },
    ),
    "page-review-other": (
        "page-review",
        {
            1: lambda answer: _with_entry(answer, 2, continues_to_next_page=False),
            2: lambda answer: _with_entry(answer, 1, kind="other"),
        },
    ),
    "page-unbroken": ("happy", _unbroken()),
    "page-other-unbroken": ("page-other", _unbroken()),
    "page-no-act-unbroken": ("page-no-act", _unbroken()),
    "page-flags-disagree": (
        "happy",
        {2: lambda answer: _with_entry(answer, 1, continues_from_previous_page=False)},
    ),
    "page-runs-past-end": (
        "happy",
        _unbroken(
            {
                2: lambda answer: _with_entry(
                    answer, 1, continues_from_previous_page=False, continues_to_next_page=True
                )
            }
        ),
    ),
    "witness-capabilities": ("happy", {}),
    "churro-native": ("happy", {2: _citing_no_churro_unit}),
    "churro-truncation": ("happy", {}),
    "refused-page": ("happy", {}),
    "refused-first-page": ("happy", {}),
    "structure-failure": ("happy", {}),
    "genuinely-empty-witness": ("happy", {1: _citing_no_churro_unit}),
    "not-run-witness": ("happy", {1: _citing_no_churro_unit}),
    "malformed-witness": ("happy", {1: _citing_no_churro_unit}),
    "malformed-capabilities": ("happy", {1: _citing_no_churro_unit}),
    "ink-free-page": ("happy", {}),
    "ink-free-page-unwitnessed": ("happy", {}),
}
PAGE_ANSWERS += tuple(
    {
        **row,
        "scenario": variant,
        "answer": pages[row["page_ordinal"]](row["answer"])
        if callable(pages.get(row["page_ordinal"]))
        else pages.get(row["page_ordinal"], row["answer"]),
    }
    for variant, (base, pages) in PAGE_ANSWER_VARIANTS.items()
    for row in PAGE_ANSWERS
    if row["scenario"] == base
) + tuple(
    # The ink-free page is read as blank paper: nothing on it to cite.
    {"scenario": scenario, "page_ordinal": 3, "answer": {"acts": [], "set_aside": []}}
    for scenario in ("ink-free-page", "ink-free-page-unwitnessed")
)


# Page responses derive from the act declarations so they cannot drift.
# config/models.toml owns page scope; tests reconcile the two.
_PAGE_ACTS = {1: ("a1", "a2"), 2: ("a2",)}


def churro_xml(text: str) -> str:
    """Frame fixture text as Churro XML; it is not a measured model response."""
    if "<" in text or ">" in text or "&" in text:
        raise ValueError("a declared Churro response text must not need XML escaping")
    return f"<output>{text}</output>"


def _joined_page_text(page_ordinal: int, chair: str) -> str:
    """Keep the pinned happy page text derived from its act testimony."""
    return "\n".join(TESTIMONY[act_key][chair] for act_key in _PAGE_ACTS[page_ordinal])


# Page furniture makes assumed act-order attachment observably wrong.
_CHURRO_NATIVE_HEADER = "[FOLIO RUBRIC 7 -- page furniture, belongs to no entry]"


def _churro_native_page_text(page_ordinal: int, chair: str) -> str:
    return f"{_CHURRO_NATIVE_HEADER}\n{_joined_page_text(page_ordinal, chair)}"


# The whole-page chairs: Chandra and Churro answer each page in one response;
# DAI (attestator_2) answers record by record (DAI_RECORD_RESPONSES).
CHANDRA_CHAIR = "attestator_1"
CHURRO_CHAIR = "attestator_3"

# Churro's answer to every page, in its own grammar; a scenario row replaces it.
# Only attestator_3's boundary is churro.v1; declared-response validation refuses a
# Churro response attributed to another chair.
CHURRO_PAGE_RESPONSES = tuple(
    {
        "page_ordinal": page_ordinal,
        "chair": CHURRO_CHAIR,
        "raw_xml": churro_xml(_joined_page_text(page_ordinal, CHURRO_CHAIR)),
        "transport_stop_reason": "eos",
    }
    for page_ordinal in sorted(_PAGE_ACTS)
) + (
    {
        "scenario": "churro-native",
        "page_ordinal": 1,
        "chair": "attestator_3",
        "raw_xml": churro_xml(_churro_native_page_text(1, "attestator_3")),
        "transport_stop_reason": "eos",
    },
    {
        "scenario": "churro-native",
        "page_ordinal": 2,
        "chair": "attestator_3",
        # A parse failure must be cut inside the grammar: the reader treats a
        # body with no grammar as plain text, not as malformed.
        "raw_xml": (
            f"<HistoricalDocument><Page><Body><Line>{_churro_native_page_text(2, 'attestator_3')}"
        ),
        "transport_stop_reason": "length",
    },
    {
        "scenario": "churro-truncation",
        "page_ordinal": 1,
        "chair": "attestator_3",
        "raw_xml": churro_xml(_churro_native_page_text(1, "attestator_3")),
        "transport_stop_reason": "eos",
    },
    {
        "scenario": "churro-truncation",
        "page_ordinal": 2,
        # Cut at `length` but valid: the text is kept, marked truncated.
        "chair": "attestator_3",
        "raw_xml": churro_xml(_churro_native_page_text(2, "attestator_3")),
        "transport_stop_reason": "length",
    },
)


def chandra_page_testimony(page_ordinal: int) -> dict[str, Any]:
    """Chandra's declared answer to one page: its acts' text, one placeholder per act.

    Each act whose proposal lies on the page is one JSON placeholder binding its
    text to native geometry over the act, which the page feed shows as one
    boxed unit; a page holding only a continuation carries the text alone.
    """
    row: dict[str, Any] = {
        "page_ordinal": page_ordinal,
        "chair": CHANDRA_CHAIR,
        "payload": _joined_page_text(page_ordinal, CHANDRA_CHAIR),
    }
    placed = [
        act["key"]
        for act in ACTS
        if act["key"] in _PAGE_ACTS[page_ordinal] and act["page_ordinal"] == page_ordinal
    ]
    if placed:
        # Float boxes stay raw; only the Chandra adapter quantizes them.
        row["raw_responses"] = [
            chandra_raw_response_for_act(TESTIMONY[act_key][CHANDRA_CHAIR], act_key)
            for act_key in placed
        ]
    return row


# What a whole-page chair returned for one page, one row per page and chair; a
# scenario row replaces the unscoped one. `witness-capabilities` exercises
# `format_capabilities`: a witness that cannot say "unsure" must not be read as
# confident, so Chandra cannot express uncertainty yet claims high confidence.
# `malformed-capabilities` declares a capability record that is not an object.
PAGE_TESTIMONY = tuple(
    chandra_page_testimony(page_ordinal) for page_ordinal in sorted(_PAGE_ACTS)
) + (
    {
        "scenario": "witness-capabilities",
        **chandra_page_testimony(1),
        "witness_reported": {"confidence": "high"},
        "format_capabilities": {"can_express_uncertainty": False, "can_express_layout": False},
    },
    {
        "scenario": "malformed-capabilities",
        "page_ordinal": 1,
        "chair": CHURRO_CHAIR,
        "payload": _joined_page_text(1, CHURRO_CHAIR),
        "format_capabilities": "provider supplied a non-object capability declaration",
    },
)

# Each row declares one empty provider response, not an outcome; the Attestatores
# derives `genuinely-empty` from it, and no other path reaches that outcome. The
# ink-free page is declared per chair, so no chair is recorded as reading a page
# it was never asked about; `ink-free-page-unwitnessed` is the same page without
# these rows.
WITNESS_EMPTY = (
    {"scenario": "genuinely-empty-witness", "page_ordinal": 1, "chair": CHURRO_CHAIR},
    {"scenario": "ink-free-page", "page_ordinal": 3, "chair": CHANDRA_CHAIR},
    {"scenario": "ink-free-page", "page_ordinal": 3, "chair": CHURRO_CHAIR},
)
WITNESS_NOT_RUN = ({"scenario": "not-run-witness", "page_ordinal": 1, "chair": CHURRO_CHAIR},)
WITNESS_MALFORMED = (
    {
        "scenario": "malformed-witness",
        "page_ordinal": 1,
        "chair": CHURRO_CHAIR,
        "reason": "fixture declares an invalid UTF-8 provider body",
    },
)

# Every scenario and what it departs from `happy` in; each reads `happy`'s rows
# except where a table above names it.
SCENARIOS = (
    ("happy", None),
    (
        "witness-capabilities",
        "Chandra reports its own confidence and format capabilities on page 1; both "
        "are retained as testimony and grade nothing.",
    ),
    (
        "page-review",
        "Its page 2 answer cites no boxed id, so the page accounting holds that entry.",
    ),
    (
        "page-no-act",
        "Its page 2 answer names one `other` entry and no act, on a page the record "
        "detector finds nothing on.",
    ),
    (
        "page-other",
        "Its page 1 answer reads a1 as `other`, over which the record detector finds no record.",
    ),
    *(
        (variant, f"{base}, answered otherwise (PAGE_ANSWER_VARIANTS).")
        for variant, (base, _pages) in PAGE_ANSWER_VARIANTS.items()
        if variant.startswith("page-")
    ),
    (
        "churro-native",
        "Two real-format Churro page responses: one that parses, and one the provider "
        "cut mid-element, retained unparseable.",
    ),
    (
        "churro-truncation",
        "A visibly cut, still-parseable Churro response: the transport said `length`, "
        "the text is kept, truncated is true, and nothing completes or re-asks it.",
    ),
    ("refused-page", "The Door refuses page 2: no witness and no reader is shown it."),
    ("refused-first-page", "The Door refuses page 1, the page both acts start on."),
    (
        "genuinely-empty-witness",
        "Churro returns an empty body for page 1: a completed empty reading, never a "
        "missing or failed attempt.",
    ),
    (
        "structure-failure",
        "The structure chair's recorded failure: the Designator holds page 1 visibly.",
    ),
    (
        "ink-free-page",
        "A third, scenario-only page of uniform paper with no declared act; every chair "
        "reads it and returns nothing.",
    ),
    (
        "ink-free-page-unwitnessed",
        "The same page with no response declared for it: Chandra and Churro end `not-run`.",
    ),
    ("not-run-witness", "Churro is never asked about page 1."),
    (
        "malformed-witness",
        "Churro's page 1 body could not be retained: a failed attempt that holds no other witness.",
    ),
    (
        "malformed-capabilities",
        "Churro's page 1 response declares a capability record that is not an object.",
    ),
)


# What Surya's two detectors report on the synthetic pages, for a run that
# configures the Surya chair against a fixture row: a text line over every
# 20-row band of each act's ink, and one `Text` layout block per act, in reading
# order down the page. Page 3 carries no ink, so Surya reports nothing there.
# Corners are whole pixels, because the sealed fixture carries no floats; the
# right and bottom corners sit on the act's far edge, as Surya's do.
SURYA_LINE_BAND_PX = 20


def _surya_polygon(x0: int, y0: int, x1: int, y1: int) -> list[list[int]]:
    return [[x0, y0], [x1, y0], [x1, y1], [x0, y1]]


SURYA_LINES = tuple(
    {
        "page_ordinal": page["ordinal"],
        "polygon": _surya_polygon(
            act["bounds"]["x"],
            act["bounds"]["y"] + band,
            act["bounds"]["x"] + act["bounds"]["w"],
            act["bounds"]["y"] + min(band + SURYA_LINE_BAND_PX, act["bounds"]["h"]),
        ),
        "confidence_bp": 9000 + 100 * act["ordinal"] + band // SURYA_LINE_BAND_PX,
    }
    for page in ALL_PAGES
    for act in page["acts"]
    for band in range(0, act["bounds"]["h"], SURYA_LINE_BAND_PX)
)
SURYA_BLOCKS = tuple(
    {
        "page_ordinal": page["ordinal"],
        "polygon": _surya_polygon(
            act["bounds"]["x"],
            act["bounds"]["y"],
            act["bounds"]["x"] + act["bounds"]["w"],
            act["bounds"]["y"] + act["bounds"]["h"],
        ),
        "label": "Text",
        "raw_label": "Text",
        "position": position,
        "confidence_bp": 9500 - position,
    }
    for page in ALL_PAGES
    for position, act in enumerate(sorted(page["acts"], key=lambda act: act["bounds"]["y"]))
)


# What DAI's own project's record detector finds on the synthetic pages: one
# record over each act's ink, inset from the act's bounds, in the order the acts
# sit down the page. Page 3 carries no ink, so the detector finds nothing there.
# Two scenarios declare records of their own, which replace these: `page-other`
# finds no record over a1, and `page-no-act` none on page 2 (`_SCENARIO_RECORDS`).
DETECTOR_RECORD_INSET_PX = 5
_SCENARIO_RECORDS = {"page-other": {1: ("a2",), 2: ("a2",)}, "page-no-act": {1: ("a1", "a2")}}
_SCENARIO_RECORDS |= {
    variant: _SCENARIO_RECORDS[base]
    for variant, (base, _pages) in PAGE_ANSWER_VARIANTS.items()
    if base in _SCENARIO_RECORDS
}


def _page_records(pages: dict[int, tuple[str, ...]]) -> tuple:
    """`(page_ordinal, detector_ordinal, bounds, act_key)` for each record on `pages`."""
    return tuple(
        (page["ordinal"], position, bounds, act_key)
        for page in ALL_PAGES
        for position, (act_key, bounds) in enumerate(
            (act_key, act["bounds"])
            for act, act_key in zip(
                sorted(page["acts"], key=lambda act: act["bounds"]["y"]),
                _PAGE_ACTS.get(page["ordinal"], ()),
                strict=True,
            )
            if act_key in pages.get(page["ordinal"], ())
        )
    )


_RECORDS_BY_SCENARIO = {None: _page_records(_PAGE_ACTS)} | {
    scenario: _page_records(pages) for scenario, pages in _SCENARIO_RECORDS.items()
}
DETECTOR_RECORDS = tuple(
    {
        **({} if scenario is None else {"scenario": scenario}),
        "page_ordinal": page_ordinal,
        "corners": _surya_polygon(
            bounds["x"] + DETECTOR_RECORD_INSET_PX,
            bounds["y"] + DETECTOR_RECORD_INSET_PX,
            bounds["x"] + bounds["w"] - DETECTOR_RECORD_INSET_PX,
            bounds["y"] + bounds["h"] - DETECTOR_RECORD_INSET_PX,
        ),
        "score_bp": 9500 - position,
    }
    for scenario, records in _RECORDS_BY_SCENARIO.items()
    for page_ordinal, position, bounds, _act_key in records
)
# What DAI (attestator_2) answers for each record it is shown: its testimony for
# the act whose ink the record covers. A scenario's own answer replaces the
# unscoped one for the same record, so only an answer that differs is scoped.
_BASE_ANSWERS = {
    (page_ordinal, position): act_key
    for page_ordinal, position, _bounds, act_key in _RECORDS_BY_SCENARIO[None]
}
DAI_RECORD_RESPONSES = tuple(
    {
        **({} if scenario is None else {"scenario": scenario}),
        "page_ordinal": page_ordinal,
        "detector_ordinal": position,
        "chair": "attestator_2",
        "text": TESTIMONY[act_key]["attestator_2"],
    }
    for scenario, records in _RECORDS_BY_SCENARIO.items()
    for page_ordinal, position, _bounds, act_key in records
    if scenario is None or _BASE_ANSWERS.get((page_ordinal, position)) != act_key
)


def page_descriptor(ordinal):
    for page in ALL_PAGES:
        if page["ordinal"] == ordinal:
            return page
    raise ValueError(f"no page {ordinal}")


def act_descriptor(page_ordinal, proposal_ordinal):
    for act in page_descriptor(page_ordinal)["acts"]:
        if act["ordinal"] == proposal_ordinal:
            return act
    raise ValueError(f"no act {proposal_ordinal} on page {page_ordinal}")


def render_all() -> dict[int, bytes]:
    return {page["ordinal"]: render_page(page) for page in ALL_PAGES}


def toml_string(value: str) -> str:
    """Encode a TOML basic string without changing its Unicode text."""
    # JSON escapes C0 controls; TOML also forbids a literal U+007F.
    return json.dumps(value, ensure_ascii=False).replace("\x7f", "\\u007F")


def toml_value(value) -> str:
    """The small JSON-native subset the synthetic Testimonium fixture needs."""
    if isinstance(value, str):
        return toml_string(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    if isinstance(value, dict):
        if not all(isinstance(key, str) for key in value):
            raise ValueError("fixture TOML object keys must be strings")
        if unsafe := [key for key in value if _BARE_TOML_KEY.fullmatch(key) is None]:
            raise ValueError(f"fixture TOML object keys must be bare-safe: {unsafe!r}")
        fields = ", ".join(f"{key} = {toml_value(item)}" for key, item in sorted(value.items()))
        return "{ " + fields + " }"
    raise ValueError(f"fixture cannot render TOML value {value!r}")


def build_ingress_manifest(rendered: dict[int, bytes]) -> str:
    lines = [
        "version = 1",
        "",
        "# A public-safe proof image is added as an exact [[fixture]] entry carrying:",
        "# path, sha256, bytes, media_type, source, and reason. The ingress check accepts",
        "# JPEG, PNG, and TIFF only when all six fields match the staged image exactly.",
        "",
        "# These are generated by proof/build_fixture.py from proof/synthetic_pages.py.",
        "# They contain no register material of any kind: they are abstract synthetic",
        "# marks, drawn by a few dozen lines of zlib and struct, and they are the only",
        "# input the walking skeleton has.",
    ]
    import hashlib

    for ordinal in sorted(rendered):
        data = rendered[ordinal]
        lines += [
            "",
            "[[fixture]]",
            f'path = "proof/fixtures/{FIXTURE_ID}/page-{ordinal}.png"',
            f'sha256 = "{hashlib.sha256(data).hexdigest()}"',
            f"bytes = {len(data)}",
            'media_type = "image/png"',
            f'source = "generated by proof/build_fixture.py, fixture {FIXTURE_ID}"',
            'reason = "synthetic walking-skeleton input; public-safe by construction"',
        ]
    return "\n".join(lines) + "\n"


def build_skeleton_fixture(rendered: dict[int, bytes]) -> str:
    import hashlib

    lines = [
        "# The pipeline's declaration of the synthetic fixture.",
        "#",
        "# Read as data by every stage program, never imported: stages exchange",
        "# artifacts on disk and import only common/, so a fixture that arrived as",
        "# Python would be a stage coupling itself to another package through a side",
        "# door. Generated by proof/build_fixture.py -- edit that, not this.",
        "",
        f"fixture_id = {toml_string(FIXTURE_ID)}",
        "# Model chairs, witness floor, and serving recipes are owned by",
        "# config/models.toml. This fixture contains only synthetic fixture data.",
    ]

    for ordinal in sorted(rendered):
        page = page_descriptor(ordinal)
        data = rendered[ordinal]
        lines += [
            "",
            "[[page]]",
            f"ordinal = {ordinal}",
            f'path = "fixtures/{FIXTURE_ID}/page-{ordinal}.png"',
            f'sha256 = "{hashlib.sha256(data).hexdigest()}"',
            f"width = {page['width']}",
            f"height = {page['height']}",
        ]
        if scenarios := page.get("scenarios"):
            lines.append("scenarios = [" + ", ".join(toml_string(item) for item in scenarios) + "]")

    for act in ACTS:
        source = act_descriptor(act["page_ordinal"], act["proposal_ordinal"])
        bounds = source["bounds"]
        lines += [
            "",
            "[[act]]",
            f"key = {toml_string(act['key'])}",
            f"page_ordinal = {act['page_ordinal']}",
            f"proposal_ordinal = {act['proposal_ordinal']}",
            f"x = {bounds['x']}",
            f"y = {bounds['y']}",
            f"w = {bounds['w']}",
            f"h = {bounds['h']}",
            f"text = {toml_string(act['text'])}",
        ]

    for observation in NATIVE_OBSERVATIONS:
        lines += ["", "[[native_observation]]"]
        for key in ("scenario", "chair", "page_ordinal", "x", "y", "w", "h"):
            if key not in observation:
                continue
            value = observation[key]
            lines.append(f"{key} = {toml_string(value) if isinstance(value, str) else value}")

    for row in SURYA_LINES:
        lines += ["", "[[surya_line]]"]
        lines += [f"{key} = {toml_value(value)}" for key, value in row.items()]

    for row in SURYA_BLOCKS:
        lines += ["", "[[surya_block]]"]
        lines += [f"{key} = {toml_value(value)}" for key, value in row.items()]

    # a2 continues across the page break: a region of the same act, not a new act.
    continuation_source = act_descriptor(2, 1)
    lines += [
        "",
        "[[continuation]]",
        'act_key = "a2"',
        "page_ordinal = 2",
        f"x = {continuation_source['bounds']['x']}",
        f"y = {continuation_source['bounds']['y']}",
        f"w = {continuation_source['bounds']['w']}",
        f"h = {continuation_source['bounds']['h']}",
    ]

    for row in PAGE_TESTIMONY:
        lines += ["", "[[testimony]]"]
        lines += [
            f"{key} = {toml_value(row[key])}"
            for key in (
                "scenario",
                "page_ordinal",
                "chair",
                "payload",
                "raw_responses",
                "witness_reported",
                "format_capabilities",
            )
            if key in row
        ]

    for row in CHURRO_PAGE_RESPONSES:
        lines += [
            "",
            "[[churro_page_response]]",
            *([f"scenario = {toml_string(row['scenario'])}"] if "scenario" in row else []),
            f"page_ordinal = {row['page_ordinal']}",
            f"chair = {toml_string(row['chair'])}",
            f"raw_xml = {toml_string(row['raw_xml'])}",
            f"transport_stop_reason = {toml_string(row['transport_stop_reason'])}",
        ]

    for row in DETECTOR_RECORDS:
        lines += [
            "",
            "[[detector_record]]",
            *([f"scenario = {toml_string(row['scenario'])}"] if "scenario" in row else []),
            f"page_ordinal = {row['page_ordinal']}",
            f"corners = {toml_value(row['corners'])}",
            f"score_bp = {row['score_bp']}",
        ]

    for row in DAI_RECORD_RESPONSES:
        lines += [
            "",
            "[[dai_record_response]]",
            *([f"scenario = {toml_string(row['scenario'])}"] if "scenario" in row else []),
            f"page_ordinal = {row['page_ordinal']}",
            f"detector_ordinal = {row['detector_ordinal']}",
            f"chair = {toml_string(row['chair'])}",
            f"text = {toml_string(row['text'])}",
        ]

    for name, departure in SCENARIOS:
        lines += [""]
        if departure is not None:
            lines += [f"# {name}: {departure}"]
        lines += ["[[scenario]]", f"name = {toml_string(name)}"]
    lines += [
        "",
        "# The fake Perlector's answer to a whole-page reading, one per scenario and page.",
        "# `answer` is the reply text exactly.",
        "",
    ]
    for row in PAGE_ANSWERS:
        lines += [
            "[[page_answer]]",
            f"scenario = {toml_string(row['scenario'])}",
            f"page_ordinal = {row['page_ordinal']}",
            "answer = "
            + toml_string(
                row["answer"]
                if isinstance(row["answer"], str)
                else json.dumps(row["answer"], separators=(",", ":"))
            ),
            "",
        ]
    for table, rows in (
        ("witness_empty", WITNESS_EMPTY),
        ("witness_not_run", WITNESS_NOT_RUN),
        ("witness_malformed", WITNESS_MALFORMED),
    ):
        for row in rows:
            lines += ["", f"[[{table}]]"]
            lines += [f"{key} = {toml_value(value)}" for key, value in row.items()]

    for row in STRUCTURE_FAILURES:
        lines += [
            "",
            "# A recorded structure-chair failure: the Designator holds the page and every",
            "# act that needed it, with the reason named, rather than skipping either.",
            "",
            "[[structure_failure]]",
            f"scenario = {toml_string(row['scenario'])}",
            f"page_ordinal = {row['page_ordinal']}",
            f"reason_code = {toml_string(row['reason_code'])}",
        ]

    lines += [
        "",
        "# Per-scenario declared digests the checked-in bytes cannot match, so the",
        "# door refuses those pages through its real inspection path. The declared",
        "# digest is all zeros: unmistakably not the digest of anything here.",
    ]
    for refusal in PAGE_REFUSALS:
        lines += [
            "",
            "[[page_refusal]]",
            f"scenario = {toml_string(refusal['scenario'])}",
            f"ordinal = {refusal['ordinal']}",
            f"declared_sha256 = {toml_string(_UNMATCHABLE_SHA256)}",
        ]
    return "\n".join(lines) + "\n"


def main() -> int:
    rendered = render_all()

    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
    for ordinal, data in sorted(rendered.items()):
        (FIXTURE_DIR / f"page-{ordinal}.png").write_bytes(data)

    (PROOF_ROOT / "fixtures.toml").write_text(build_ingress_manifest(rendered), encoding="utf-8")
    (PROOF_ROOT / "skeleton_fixture.toml").write_text(
        build_skeleton_fixture(rendered), encoding="utf-8"
    )

    # Fail here if a crop the pipeline will take is not derivable.
    for act in ACTS:
        source = act_descriptor(act["page_ordinal"], act["proposal_ordinal"])
        crop_png(rendered[act["page_ordinal"]], source["bounds"])

    print(f"wrote {len(rendered)} pages, fixtures.toml and skeleton_fixture.toml for {FIXTURE_ID}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
