"""Render the declared proof pages and write both declarations that describe them.

Run from the repository root:

    python3 proof/build_fixture.py

It writes three things and nothing else:

  proof/fixtures/<fixture-id>/page-N.png   the checked-in bytes themselves
  proof/fixtures.toml                      the ingress declaration the hook enforces
  proof/skeleton_fixture.toml              the pipeline's declaration of what is on them

**The checked-in bytes are the authority, not this script.** Spec 01 asks for fixed
checked-in bytes with expected digests precisely so that encoders, fonts and
metadata cannot vary across machines — and zlib's exact output, while a pure
function of its input for a given implementation, is not guaranteed identical
across zlib builds. So a machine whose regenerated bytes differ has not found a
defect in the fixture; it has found a different zlib. The test beside this script
asserts what actually matters and holds everywhere: the checked-in files decode to
exactly the pixels this generator describes.

Two declarations rather than one because they answer different questions and are
read by different things. `fixtures.toml` answers "may these bytes be in git?" and
is enforced by the ingress hook on every commit and push. `skeleton_fixture.toml`
answers "what is on these pages, and what should the fakes do?" and is read by the
stage programs as data.
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from common.imaging import crop_png  # noqa: E402
from proof.synthetic_pages import ALL_PAGES, FIXTURE_ID, render_page  # noqa: E402

PROOF_ROOT = Path(__file__).resolve().parent
FIXTURE_DIR = PROOF_ROOT / "fixtures" / FIXTURE_ID
_BARE_TOML_KEY = re.compile(r"^[A-Za-z0-9_-]+$")

# What the fake Perlector establishes for each act. Fixture-defined text proving
# structural wiring only: it says nothing whatever about reading ink, and the
# skeleton's report may not pretend otherwise.
ACTS = (
    {
        "key": "a1",
        "page_ordinal": 1,
        "proposal_ordinal": 0,
        "text": "SYNTHETIC ACT ONE alpha beta gamma",
    },
    {
        "key": "a2",
        "page_ordinal": 1,
        "proposal_ordinal": 1,
        "text": "SYNTHETIC ACT TWO delta epsilon zeta eta",
    },
)

# Pass A is independently declared per scenario and act. Both core scenarios
# deliberately contain one real departure and one equality: the instrument is
# capable of measuring a self-revision without treating disagreement as success.
#
# Every scenario whose acts reach the Perlector at all must declare its own
# prior reading -- there is no cross-scenario fallback (FixtureReader refuses
# by name instead of silently borrowing another scenario's declaration, which
# would let an undeclared scenario measure a self-revision nobody wrote down).
# `refused-first-page` and `structure-failure` hold every act before the
# Perlector runs and are the only scenarios that do not need one.
_DEFAULT_PRIOR_TEXT = {
    "a1": "SYNTHETIC ACT ONE alpha beta ganna",
    "a2": "SYNTHETIC ACT TWO delta epsilon zeta eta",
}
_PRIOR_READING_SCENARIOS = (
    "happy",
    "witness-capabilities",
    "review",
    "refused-page",
    "truncated-reading",
    "genuinely-empty-witness",
    "confirmed-blank",
    "blank-with-dissent",
    "engine-truncated-reading",
    "no-readable-text-reading",
    "ink-free-page",
    "reread-failure",
    "reread-success",
    "not-run-witness",
    "malformed-witness",
    "structured-witness",
    "malformed-capabilities",
)
PRIOR_READINGS = tuple(
    {"scenario": scenario, "act_key": act_key, "text": text}
    for scenario in _PRIOR_READING_SCENARIOS
    for act_key, text in _DEFAULT_PRIOR_TEXT.items()
)

# What each witness reports. Chair 1 agrees with the established reading, chair 2
# differs in one token and chair 3 stops short — so the recorded dissent is
# structural and non-trivial rather than uniformly empty. Dissent is not a
# quality signal (ARCHITECTURE, "On dissent"); it is here so the *shape* of the
# record is exercised.
TESTIMONY = {
    "a1": {
        "attestator_1": "SYNTHETIC ACT ONE alpha beta gamma",
        "attestator_2": "SYNTHETIC ACT ONE alpha beta gamna",
        "attestator_3": "SYNTHETIC ACT ONE alpha beta",
    },
    "a2": {
        "attestator_1": "SYNTHETIC ACT TWO delta epsilon zeta eta",
        "attestator_2": "SYNTHETIC ACT TWO delta epsilon zeta",
        "attestator_3": "SYNTHETIC ACT TWO delta epsiIon zeta eta",
    },
}

# The first two rows are the pair spec 07's `format_capabilities` exists for: "a
# witness that cannot say 'unsure' must not be read as confident". Their own
# `witness-capabilities` scenario keeps that distinction exercised without
# leaving one of the reference happy run's three chairs uncompared in its dissent
# record. Chair 1's format cannot express uncertainty and its self-report claims
# high confidence anyway; chair 2's can, and reports doubt. Declaring one side
# only would leave the distinction representable but never exercised, which is
# where a later reader starts treating a self-report as evidence. The structured
# row exercises the schema without pretending the text-only Perlector bridge can
# consume it: a stage 3 boundary fixture, not an end-to-end surface.
SCENARIO_TESTIMONY = (
    {
        "scenario": "witness-capabilities",
        "act_key": "a1",
        "chair": "attestator_1",
        "payload": TESTIMONY["a1"]["attestator_1"],
        "witness_reported": {"confidence": "high"},
        "format_capabilities": {"can_express_uncertainty": False, "can_express_layout": False},
    },
    {
        "scenario": "witness-capabilities",
        "act_key": "a1",
        "chair": "attestator_2",
        "payload": TESTIMONY["a1"]["attestator_2"],
        "witness_reported": {"confidence": "low", "note": "faded ink"},
        "format_capabilities": {"can_express_uncertainty": True, "can_express_layout": False},
    },
    {
        "scenario": "structured-witness",
        "act_key": "a1",
        "chair": "attestator_1",
        "payload": {"tokens": ["μ", "beta"], "layout": {"line": 4}, "uncertain": True},
        "witness_reported": {"confidence": "certain", "note": "witness claim only"},
    },
    {
        "scenario": "malformed-capabilities",
        "act_key": "a1",
        "chair": "attestator_3",
        "payload": "SYNTHETIC ACT ONE alpha beta",
        "format_capabilities": "provider supplied a non-object capability declaration",
    },
    {
        "scenario": "reread-success",
        "act_key": "a2",
        "chair": "attestator_1",
        "attempt_ordinal": 2,
        "payload": "SYNTHETIC ACT TWO delta epsilon zeta eta, reread",
    },
)

# The recovery region for the review scenario: an expanded recrop of act a1. It
# must stay inside the page and must not reach into act a2's bounds, or the
# recovery would be inventing an overlap rather than widening a crop.
RECOVERY_BOUNDS = {"a1": {"x": 16, "y": 16, "w": 168, "h": 88}}

# Per-scenario declared digests that will not match the checked-in bytes, so the
# door refuses the page honestly through its real inspection path rather than
# through any scenario-aware branch. The declared value is deliberately a digest
# nothing can hash to collide with by accident here: all zeros.
PAGE_REFUSALS = (
    {"scenario": "refused-page", "ordinal": 2},
    {"scenario": "refused-first-page", "ordinal": 1},
)
WITNESS_EMPTY = (
    {"scenario": "genuinely-empty-witness", "act_key": "a1", "chair": "attestator_3"},
    # All three configured chairs, so the Recensor's blank corroboration has a
    # genuine unanimous absence to confirm -- not merely one dissenting-from-
    # nothing chair beside two that never ran.
    {"scenario": "confirmed-blank", "act_key": "a1", "chair": "attestator_1"},
    {"scenario": "confirmed-blank", "act_key": "a1", "chair": "attestator_2"},
    {"scenario": "confirmed-blank", "act_key": "a1", "chair": "attestator_3"},
    # Two of three: the third chair is left to report its ordinary declared
    # testimony (real text), so blank corroboration must refuse -- a single
    # dissenting witness beside an identical Perlector `no-readable-text`.
    {"scenario": "blank-with-dissent", "act_key": "a1", "chair": "attestator_1"},
    {"scenario": "blank-with-dissent", "act_key": "a1", "chair": "attestator_2"},
)

# A page the structure pass could not mark out. Spec 06 asks for this exact case
# by name: "A page the structure seat fails on is **held visibly** and
# recoverable ... never silently skipped". It is a *recorded* failure rather than
# a live one because there is no live structure model here to fail; what is real
# is everything downstream of it — the page's held structure-status record, the
# hold artifact on every act that needed the page, and the act's continued
# presence in the proposal seal.
STRUCTURE_FAILURES = (
    {
        "scenario": "structure-failure",
        "page_ordinal": 1,
        "reason_code": "recorded-fixture-structure-failure",
    },
)

WITNESS_FAILURES = (
    {"scenario": "review", "act_key": "a2", "chair": "attestator_3", "attempt_ordinal": 1},
    {
        "scenario": "reread-failure",
        "act_key": "a1",
        "chair": "attestator_3",
        "attempt_ordinal": 2,
    },
)
WITNESS_NOT_RUN = ({"scenario": "not-run-witness", "act_key": "a1", "chair": "attestator_3"},)
WITNESS_MALFORMED = (
    {
        "scenario": "malformed-witness",
        "act_key": "a1",
        "chair": "attestator_3",
        "reason": "fixture declares an invalid UTF-8 provider body",
    },
)
_UNMATCHABLE_SHA256 = "0" * 64

# A reading that did not succeed but still carries text -- the hazard
# `truncated-reading` exercises: a `truncated` Perlectio must be held rather
# than established. `no-readable-text-reading` exercises the sibling hazard,
# an act the Perlector could not read at all: unresolved, not failed, and the
# Perlector forces its own reading text to the empty string rather than
# leaving the fixture's normal act text sitting underneath a declared silence.
READING_FAILURES = (
    {"scenario": "truncated-reading", "act_key": "a1", "outcome": "truncated"},
    {"scenario": "no-readable-text-reading", "act_key": "a1", "outcome": "no-readable-text"},
)

# The one declared, fixture-only truncation signal (`pipeline/4_perlector/
# truncation.py`): a real serving engine's own stop-reason, which this offline
# skeleton has none of to observe honestly. `engine-truncated-reading`
# exercises the detector's own authority -- unlike `truncated-reading` above,
# nothing here declares the outcome directly; the Perlector must derive
# `truncated` from the engine signal alone.
STOP_REASONS = ({"scenario": "engine-truncated-reading", "act_key": "a1", "stop_reason": "length"},)


def page_descriptor(ordinal):
    for page in ALL_PAGES:
        if page["ordinal"] == ordinal:
            return page
    raise ValueError(f"no page {ordinal}")


def act_descriptor(page_ordinal, proposal_ordinal):
    for act in page_descriptor(page_ordinal)["acts"]:
        if act["ordinal"] == proposal_ordinal:
            return act
    raise ValueError(f"no act {proposal_ordinal} on page {page_ordinal}")


def render_all() -> dict[int, bytes]:
    return {page["ordinal"]: render_page(page) for page in ALL_PAGES}


def toml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def toml_value(value) -> str:
    """The small JSON-native subset the synthetic Testimonium fixture needs."""
    if isinstance(value, str):
        return toml_string(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    if isinstance(value, dict):
        if not all(isinstance(key, str) for key in value):
            raise ValueError("fixture TOML object keys must be strings")
        if unsafe := [key for key in value if _BARE_TOML_KEY.fullmatch(key) is None]:
            raise ValueError(f"fixture TOML object keys must be bare-safe: {unsafe!r}")
        fields = ", ".join(f"{key} = {toml_value(item)}" for key, item in sorted(value.items()))
        return "{ " + fields + " }"
    raise ValueError(f"fixture cannot render TOML value {value!r}")


def build_ingress_manifest(rendered: dict[int, bytes]) -> str:
    lines = [
        "version = 1",
        "",
        "# A public-safe proof image is added as an exact [[fixture]] entry carrying:",
        "# path, sha256, bytes, media_type, source, and reason. The ingress check accepts",
        "# JPEG, PNG, and TIFF only when all six fields match the staged image exactly.",
        "",
        "# These are generated by proof/build_fixture.py from proof/synthetic_pages.py.",
        "# They contain no register material of any kind: they are abstract synthetic",
        "# marks, drawn by a few dozen lines of zlib and struct, and they are the only",
        "# input the walking skeleton has.",
    ]
    import hashlib

    for ordinal in sorted(rendered):
        data = rendered[ordinal]
        lines += [
            "",
            "[[fixture]]",
            f'path = "proof/fixtures/{FIXTURE_ID}/page-{ordinal}.png"',
            f'sha256 = "{hashlib.sha256(data).hexdigest()}"',
            f"bytes = {len(data)}",
            'media_type = "image/png"',
            f'source = "generated by proof/build_fixture.py, fixture {FIXTURE_ID}"',
            'reason = "synthetic walking-skeleton input; public-safe by construction"',
        ]
    return "\n".join(lines) + "\n"


def build_skeleton_fixture(rendered: dict[int, bytes]) -> str:
    import hashlib

    lines = [
        "# The pipeline's declaration of the synthetic fixture.",
        "#",
        "# Read as data by every stage program, never imported: stages exchange",
        "# artifacts on disk and import only common/, so a fixture that arrived as",
        "# Python would be a stage coupling itself to another package through a side",
        "# door. Generated by proof/build_fixture.py -- edit that, not this.",
        "",
        f"fixture_id = {toml_string(FIXTURE_ID)}",
        "# Model chairs, witness floor, and serving recipes are owned by",
        "# config/models.toml. This fixture contains only synthetic fixture data.",
        "# R0 declares page witnesses here; the Attestatores derives their page",
        "# Testimonia and interim whole-reading act attachments in the same invocation.",
        'page_witness_chairs = ["attestator_1", "attestator_3"]',
    ]

    for ordinal in sorted(rendered):
        page = page_descriptor(ordinal)
        data = rendered[ordinal]
        lines += [
            "",
            "[[page]]",
            f"ordinal = {ordinal}",
            f'path = "fixtures/{FIXTURE_ID}/page-{ordinal}.png"',
            f'sha256 = "{hashlib.sha256(data).hexdigest()}"',
            f"width = {page['width']}",
            f"height = {page['height']}",
        ]
        if scenarios := page.get("scenarios"):
            lines.append("scenarios = [" + ", ".join(toml_string(item) for item in scenarios) + "]")

    for act in ACTS:
        source = act_descriptor(act["page_ordinal"], act["proposal_ordinal"])
        bounds = source["bounds"]
        lines += [
            "",
            "[[act]]",
            f"key = {toml_string(act['key'])}",
            f"page_ordinal = {act['page_ordinal']}",
            f"proposal_ordinal = {act['proposal_ordinal']}",
            f"x = {bounds['x']}",
            f"y = {bounds['y']}",
            f"w = {bounds['w']}",
            f"h = {bounds['h']}",
            f"text = {toml_string(act['text'])}",
        ]

    for prior in PRIOR_READINGS:
        lines += [
            "",
            "[[prior_reading]]",
            f"scenario = {toml_string(prior['scenario'])}",
            f"act_key = {toml_string(prior['act_key'])}",
            f"text = {toml_string(prior['text'])}",
        ]

    # One act runs across the page break. The continuation is a region of the
    # same act, not a third act: two acts, one cross-page continuation.
    continuation_source = act_descriptor(2, 1)
    lines += [
        "",
        "[[continuation]]",
        'act_key = "a2"',
        "page_ordinal = 2",
        f"x = {continuation_source['bounds']['x']}",
        f"y = {continuation_source['bounds']['y']}",
        f"w = {continuation_source['bounds']['w']}",
        f"h = {continuation_source['bounds']['h']}",
    ]

    for act_key, bounds in RECOVERY_BOUNDS.items():
        lines += [
            "",
            "[[recovery]]",
            f"act_key = {toml_string(act_key)}",
            f"x = {bounds['x']}",
            f"y = {bounds['y']}",
            f"w = {bounds['w']}",
            f"h = {bounds['h']}",
        ]

    for act_key, chairs in TESTIMONY.items():
        for chair, payload in chairs.items():
            lines += [
                "",
                "[[testimony]]",
                f"act_key = {toml_string(act_key)}",
                f"chair = {toml_string(chair)}",
                f"payload = {toml_value(payload)}",
            ]

    for row in SCENARIO_TESTIMONY:
        lines += [
            "",
            "[[testimony]]",
            f"scenario = {toml_string(row['scenario'])}",
            f"act_key = {toml_string(row['act_key'])}",
            f"chair = {toml_string(row['chair'])}",
            f"payload = {toml_value(row['payload'])}",
        ]
        if "witness_reported" in row:
            lines.append(f"witness_reported = {toml_value(row['witness_reported'])}")
        if "format_capabilities" in row:
            lines.append(f"format_capabilities = {toml_value(row['format_capabilities'])}")
        if "attempt_ordinal" in row:
            lines.append(f"attempt_ordinal = {row['attempt_ordinal']}")

    lines += [
        "",
        "# The happy scenario establishes both acts. The review scenario recovers act",
        "# a1 once -- act identity stable, region and attempt identities changing -- and",
        "# holds act a2, which therefore reaches no Archetypus at all.",
        "#",
        "# The refused-page scenario loses page 2 at the door, so act a2's declared",
        "# continuation cannot be cut and the act is held rather than delivered on half",
        "# its ink. The refused-first-page scenario loses page 1, the page both acts",
        "# live on: neither act can be marked out at all, and both must still end in",
        "# exactly one terminal category with the page loss named in the aggregate.",
        "",
        "[[scenario]]",
        'name = "happy"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "[[scenario]]",
        'name = "witness-capabilities"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "[[scenario]]",
        'name = "review"',
        'recover_acts = ["a1"]',
        'hold_acts = ["a2"]',
        "",
        "[[scenario]]",
        'name = "refused-page"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "[[scenario]]",
        'name = "refused-first-page"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "[[scenario]]",
        'name = "truncated-reading"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "[[scenario]]",
        'name = "genuinely-empty-witness"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "[[scenario]]",
        'name = "confirmed-blank"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "[[scenario]]",
        'name = "blank-with-dissent"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "# engine-truncated-reading exercises the truncation detector's own",
        "# authority over a declared engine stop-reason, rather than a directly",
        "# declared reading_failure outcome (see STOP_REASONS below).",
        "",
        "[[scenario]]",
        'name = "engine-truncated-reading"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "# no-readable-text-reading exercises the sibling hazard to a truncated",
        "# reading: an act the Perlector could not read at all, rather than one",
        "# it read part of.",
        "",
        "[[scenario]]",
        'name = "no-readable-text-reading"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "[[scenario]]",
        'name = "structure-failure"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "# A third, scenario-only page is uniform paper with no declared act.",
        "# The Designator must tile it, and the witnesses and Perlector must",
        "# actually read those tiles rather than crashing on its minted act key.",
        "",
        "[[scenario]]",
        'name = "ink-free-page"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "[[scenario]]",
        'name = "reread-failure"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "[[scenario]]",
        'name = "reread-success"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "[[scenario]]",
        'name = "not-run-witness"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "[[scenario]]",
        'name = "malformed-witness"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "[[scenario]]",
        'name = "structured-witness"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "[[scenario]]",
        'name = "malformed-capabilities"',
        "recover_acts = []",
        "hold_acts = []",
        "",
        "# A reading that did not succeed. `truncated` is a failed-class Perlector",
        "# outcome that still carries text, which is the combination that matters: the",
        "# Recensor used to ask only whether a reading existed, and the Archetypus",
        "# copied the text out of whichever reading was latest. Stale text from a",
        "# reading nobody completed could therefore be established as the one text.",
        "# This scenario drives that exact path, and asserts the act is held instead.",
        "# no-readable-text-reading drives the sibling hazard: an unresolved, not",
        "# failed, outcome for an act nothing could be read from at all.",
        "",
    ]
    for failure in READING_FAILURES:
        lines += [
            "[[reading_failure]]",
            f"scenario = {toml_string(failure['scenario'])}",
            f"act_key = {toml_string(failure['act_key'])}",
            f"outcome = {toml_string(failure['outcome'])}",
            "",
        ]
    lines += [
        "# The one declared, fixture-only truncation signal: a stand-in for a real",
        "# serving engine's own stop-reason, read by",
        "# `pipeline/4_perlector/truncation.py` and authoritative for `truncated`",
        "# when it declares `length` -- named explicitly as a fixture stand-in",
        "# rather than a computed signal.",
        "",
        "# The Perlector's own direct finding of no readable text. Under",
        "# `confirmed-blank` every configured chair also independently reports",
        "# `genuinely-empty` (see WITNESS_EMPTY below), so the Recensor's blank",
        "# corroboration has unanimous evidence and may seal `confirmed-blank`.",
        "# Under `blank-with-dissent` only two of three chairs agree -- the third",
        "# reads real text -- so the identical Perlector finding must instead be",
        "# held for review: a single dissenting witness is exactly the",
        "# disagreement GOALS 1 says may never be silently resolved.",
        "",
        "[[reading_failure]]",
        'scenario = "confirmed-blank"',
        'act_key = "a1"',
        'outcome = "no-readable-text"',
        "",
        "[[reading_failure]]",
        'scenario = "blank-with-dissent"',
        'act_key = "a1"',
        'outcome = "no-readable-text"',
        "",
    ]
    for row in STOP_REASONS:
        lines += [
            "[[stop_reason]]",
            f"scenario = {toml_string(row['scenario'])}",
            f"act_key = {toml_string(row['act_key'])}",
            f"stop_reason = {toml_string(row['stop_reason'])}",
            "",
        ]
    lines += [
        "# A completed empty Testimonium means the chair read the region and found no",
        "# reportable text. It is deliberately distinct from a missing or failed attempt.",
        "",
        "# Per-scenario declared digests the checked-in bytes cannot match, so the",
        "# door refuses those pages through its real inspection path. The declared",
        "# digest is all zeros: unmistakably not the digest of anything here.",
    ]

    for row in WITNESS_EMPTY:
        lines += [
            "",
            "[[witness_empty]]",
            f"scenario = {toml_string(row['scenario'])}",
            f"act_key = {toml_string(row['act_key'])}",
            f"chair = {toml_string(row['chair'])}",
        ]

    for row in STRUCTURE_FAILURES:
        lines += [
            "",
            "# A recorded structure-chair failure: the Designator holds the page and every",
            "# act that needed it, with the reason named, rather than skipping either.",
            "",
            "[[structure_failure]]",
            f"scenario = {toml_string(row['scenario'])}",
            f"page_ordinal = {row['page_ordinal']}",
            f"reason_code = {toml_string(row['reason_code'])}",
        ]

    for row in WITNESS_FAILURES:
        lines += [
            "",
            "[[witness_failure]]",
            f"scenario = {toml_string(row['scenario'])}",
            f"act_key = {toml_string(row['act_key'])}",
            f"chair = {toml_string(row['chair'])}",
            f"attempt_ordinal = {row['attempt_ordinal']}",
        ]

    for row in WITNESS_NOT_RUN:
        lines += [
            "",
            "[[witness_not_run]]",
            f"scenario = {toml_string(row['scenario'])}",
            f"act_key = {toml_string(row['act_key'])}",
            f"chair = {toml_string(row['chair'])}",
        ]

    for row in WITNESS_MALFORMED:
        lines += [
            "",
            "[[witness_malformed]]",
            f"scenario = {toml_string(row['scenario'])}",
            f"act_key = {toml_string(row['act_key'])}",
            f"chair = {toml_string(row['chair'])}",
            f"reason = {toml_string(row['reason'])}",
        ]

    for refusal in PAGE_REFUSALS:
        lines += [
            "",
            "[[page_refusal]]",
            f"scenario = {toml_string(refusal['scenario'])}",
            f"ordinal = {refusal['ordinal']}",
            f"declared_sha256 = {toml_string(_UNMATCHABLE_SHA256)}",
        ]
    return "\n".join(lines) + "\n"


def main() -> int:
    rendered = render_all()

    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
    for ordinal, data in sorted(rendered.items()):
        (FIXTURE_DIR / f"page-{ordinal}.png").write_bytes(data)

    (PROOF_ROOT / "fixtures.toml").write_text(build_ingress_manifest(rendered), encoding="utf-8")
    (PROOF_ROOT / "skeleton_fixture.toml").write_text(
        build_skeleton_fixture(rendered), encoding="utf-8"
    )

    # Prove the crops the pipeline will take are actually derivable here, rather
    # than discovering it three stages downstream.
    for act in ACTS:
        source = act_descriptor(act["page_ordinal"], act["proposal_ordinal"])
        crop_png(rendered[act["page_ordinal"]], source["bounds"])

    print(f"wrote {len(rendered)} pages, fixtures.toml and skeleton_fixture.toml for {FIXTURE_ID}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
