"""The autoclave launcher, tested where it can be tested without an engine.

This file is deliberately NOT in `operations/autoclave/`. `pyproject.toml` puts
`autoclave` in pytest's `norecursedirs`, because the cleanroom tray holds
presumed-contaminated drafts and pytest imports what it collects. That pattern
matches a directory of that name anywhere, so a test placed beside the script
would be skipped in silence — which is the failure GOVERNANCE 2 exists to stop.

What is covered here is argument handling, path resolution and honest reporting:
everything that runs before a container engine is needed. The parts that need an
engine — build, new, collect — are covered by using the tool, not by faking a
daemon, and until that has happened `README.md` says so in as many words.
"""

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "operations" / "autoclave" / "autoclave.sh"


def run(*args, cwd=None):
    """Invoke the launcher and return the completed process.

    `sh` explicitly rather than relying on the executable bit: the script
    declares `#!/bin/sh` and the point is that it runs under a POSIX shell, not
    under whatever the caller's login shell happens to be.
    """
    return subprocess.run(
        ["sh", str(SCRIPT), *args],
        capture_output=True,
        text=True,
        cwd=cwd or ROOT,
    )


def test_script_exists_and_is_executable():
    assert SCRIPT.is_file()
    assert SCRIPT.stat().st_mode & 0o111, "launcher is not executable"


def test_help_stops_at_the_header():
    """The help text is the header comment, and must not bleed into shell code.

    It is generated by reading the file's own leading comment, so the failure
    this guards against is real: an earlier version used a fixed line range and
    printed `set -eu` and a variable assignment to the operator.
    """
    result = run("help")
    assert result.returncode == 0
    assert "autoclave.sh doctor" in result.stdout
    assert "set -eu" not in result.stdout
    assert "IMAGE_NAME=" not in result.stdout


def test_no_argument_prints_help_rather_than_failing():
    bare = run()
    assert bare.returncode == 0
    assert "Usage:" in bare.stdout


def test_unknown_command_is_refused_by_name():
    result = run("frobnicate")
    assert result.returncode != 0
    assert "frobnicate" in result.stderr


def test_doctor_reports_state_without_an_engine():
    """`doctor` must answer honestly on a machine with nothing installed.

    It is the first thing anyone runs, and a diagnostic that fails when the
    thing it diagnoses is absent tells you nothing.
    """
    result = run("doctor")
    assert result.returncode == 0
    for label in ("repository:", "output root:", "colima:", "docker CLI:", "engine:", "image:"):
        assert label in result.stdout, f"doctor did not report {label!r}"


def test_doctor_resolves_the_repository_from_the_script_not_the_caller(tmp_path):
    """Every command must work from anywhere, so the root is resolved from $0."""
    result = run("doctor", cwd=tmp_path)
    assert result.returncode == 0
    assert str(ROOT) in result.stdout


class TestTaskNames:
    """A task name becomes a container name, a directory and a git branch.

    It is validated in one place so the three cannot disagree, and the cases
    below are the ones that would otherwise produce an invalid branch ref or a
    surprising path.
    """

    def test_empty_is_refused(self):
        result = run("new", "")
        assert result.returncode != 0
        assert "required" in result.stderr

    def test_missing_is_refused(self):
        result = run("new")
        assert result.returncode != 0
        assert "required" in result.stderr

    def test_uppercase_and_underscores_are_refused(self):
        for name in ("Bad_Name", "UPPER", "has_underscore", "has space", "has/slash"):
            result = run("new", name)
            assert result.returncode != 0, f"{name!r} was accepted"
            assert "lowercase" in result.stderr

    def test_leading_or_trailing_hyphen_is_refused(self):
        for name in ("-leading", "trailing-"):
            result = run("new", name)
            assert result.returncode != 0, f"{name!r} was accepted"
            assert "hyphen" in result.stderr

    def test_a_good_name_gets_past_validation(self):
        """A well-formed name must fail for the *next* reason, not the name.

        Checked through `report`, which validates the name and then looks for a
        file — it creates nothing. An earlier version of this test called `new`,
        which was wrong twice over: a test of argument handling must not invoke a
        command that can create a container, and the assertion it made ("the run
        stops at the missing docker") silently depended on the machine having no
        container engine. It passed until an engine was installed.
        """
        result = run("report", "spec-01-contracts")
        assert result.returncode != 0
        assert "lowercase" not in result.stderr
        assert "hyphen" not in result.stderr
        # Past validation and into the real work: it is looking for the report.
        assert "report.md" in result.stderr

    def test_validation_happens_before_anything_is_created(self):
        """A rejected name must not reach the engine at all.

        `new` is the only command that creates something, so the guarantee is
        asserted where it matters: a bad name is refused by the argument check,
        never by something further down that might have had a side effect first.
        """
        result = run("new", "Bad_Name")
        assert result.returncode != 0
        assert "lowercase" in result.stderr
        assert "docker" not in result.stderr.lower()


class TestLogin:
    """Signing a vendor in is a one-time act, and it must stay one-time.

    The sign-in lands in a Docker named volume rather than the image or a bind
    mount, which is what makes it survive every container and every restart. It
    is also what keeps a live host credential out of a chamber that has network
    egress.
    """

    def test_a_missing_vendor_is_refused(self):
        result = run("login")
        assert result.returncode != 0
        assert "claude" in result.stderr and "codex" in result.stderr

    def test_an_unknown_vendor_is_refused(self):
        result = run("login", "gemini")
        assert result.returncode != 0
        assert "claude" in result.stderr and "codex" in result.stderr

    def test_the_script_names_no_credential_path_on_the_host(self):
        """The whole point is that no host credential is read or mounted.

        Asserted against the source, because the failure would be someone later
        'helpfully' bind-mounting `~/.codex` or reaching into the Keychain to
        save Tyrel a step. Both would put a live credential inside a chamber
        with network egress.
        """
        source = SCRIPT.read_text()
        for forbidden in (
            "~/.codex",
            "~/.claude",
            "$HOME/.codex",
            "$HOME/.claude",
            "security find-",
        ):
            assert forbidden not in source, f"launcher reaches for a host credential: {forbidden}"

    def test_auth_is_mounted_read_write(self):
        """Read-only would turn a one-time sign-in into a recurring one, because
        both CLIs refresh their own tokens and would have nowhere to write."""
        source = SCRIPT.read_text()
        for volume in ("AUTH_VOL_CLAUDE", "AUTH_VOL_CODEX"):
            assert f"${{{volume}}}:" in source
            assert f"${{{volume}}}:ro" not in source, f"{volume} is mounted read-only"


def test_doctor_reports_sign_in_state_for_both_vendors():
    result = run("doctor")
    assert result.returncode == 0
    assert "auth claude" in result.stdout
    assert "auth codex" in result.stdout


def test_report_names_the_path_it_looked_for():
    """A missing report says where it looked, so the operator can go and see."""
    result = run("report", "no-such-task")
    assert result.returncode != 0
    assert "no-such-task" in result.stderr
    assert "report.md" in result.stderr


def test_output_root_is_inside_the_gitignored_workbench():
    """Nothing an agent produces may show up in `git status`.

    The drawer is under `workbench/`, which is gitignored, and this asserts the
    launcher agrees with that rather than trusting the comment.
    """
    result = run("doctor")
    assert "workbench/autoclave" in result.stdout


def test_the_brief_is_not_named_claude_md_on_the_host():
    """A `CLAUDE.md` here would be read by a host session working in this tree
    and would tell it, falsely, that it is inside a container. The Dockerfile
    renames the file on the way into the image, which is the only place the
    brief's claims are true."""
    directory = ROOT / "operations" / "autoclave"
    assert (directory / "agent-brief.md").is_file()
    assert not (directory / "CLAUDE.md").exists()


def test_dockerignore_denies_everything_before_admitting_anything():
    """The deny-all form is load-bearing: `private/` holds the notification
    topic, and an exclusion list goes stale the day a new drawer is added."""
    lines = [
        line.strip()
        for line in (ROOT / ".dockerignore").read_text().splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
    assert lines[0] == "*", "the first rule must deny everything"
    assert all(line.startswith("!") for line in lines[1:]), (
        "after the deny-all, every rule must be a re-admission"
    )
    admitted = {line[1:] for line in lines[1:]}
    assert "operations/autoclave/agent-brief.md" in admitted
    assert not any(entry.startswith("private") for entry in admitted)
