"""The autoclave launcher, tested where it can be tested without an engine.

This file is deliberately NOT in `operations/autoclave/`. `pyproject.toml` puts
`autoclave` in pytest's `norecursedirs`, because the cleanroom tray holds
presumed-contaminated drafts and pytest imports what it collects. That pattern
matches a directory of that name anywhere, so a test placed beside the script
would be skipped in silence — which is the failure GOVERNANCE 2 exists to stop.

What is covered here is argument handling, path resolution and honest reporting:
everything that runs before a container engine is needed. The parts that need an
engine — build, new, collect — are covered by using the tool, not by faking a
daemon, and until that has happened `README.md` says so in as many words.
"""

import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "operations" / "autoclave" / "autoclave.sh"


def run(*args, cwd=None):
    """Invoke the launcher and return the completed process.

    `sh` explicitly rather than relying on the executable bit: the script
    declares `#!/bin/sh` and the point is that it runs under a POSIX shell, not
    under whatever the caller's login shell happens to be.
    """
    return subprocess.run(
        ["sh", str(SCRIPT), *args],
        capture_output=True,
        text=True,
        cwd=cwd or ROOT,
    )


def code_lines():
    """The launcher's runnable lines, with comments and blanks dropped.

    Several tests below assert that a dangerous flag or a known-trap invocation
    appears exactly once. Matching raw source counts the explanatory comment
    beside the code as a second occurrence, which made two of these tests fail on
    the very comments written to justify them. Shell has no block comments, so
    dropping `#` lines is sufficient and honest here.
    """
    return [
        line
        for line in SCRIPT.read_text().splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def test_script_exists_and_is_executable():
    assert SCRIPT.is_file()
    assert SCRIPT.stat().st_mode & 0o111, "launcher is not executable"


def test_help_stops_at_the_header():
    """The help text is the header comment, and must not bleed into shell code.

    It is generated by reading the file's own leading comment, so the failure
    this guards against is real: an earlier version used a fixed line range and
    printed `set -eu` and a variable assignment to the operator.
    """
    result = run("help")
    assert result.returncode == 0
    assert "autoclave.sh doctor" in result.stdout
    assert "set -eu" not in result.stdout
    assert "IMAGE_NAME=" not in result.stdout


def test_no_argument_prints_help_rather_than_failing():
    bare = run()
    assert bare.returncode == 0
    assert "Usage:" in bare.stdout


def test_unknown_command_is_refused_by_name():
    result = run("frobnicate")
    assert result.returncode != 0
    assert "frobnicate" in result.stderr


def test_doctor_reports_state_without_an_engine():
    """`doctor` must answer honestly on a machine with nothing installed.

    It is the first thing anyone runs, and a diagnostic that fails when the
    thing it diagnoses is absent tells you nothing.
    """
    result = run("doctor")
    assert result.returncode == 0
    for label in ("repository:", "output root:", "colima:", "docker CLI:", "engine:", "image:"):
        assert label in result.stdout, f"doctor did not report {label!r}"


def test_doctor_resolves_the_repository_from_the_script_not_the_caller(tmp_path):
    """Every command must work from anywhere, so the root is resolved from $0."""
    result = run("doctor", cwd=tmp_path)
    assert result.returncode == 0
    assert str(ROOT) in result.stdout


class TestTaskNames:
    """A task name becomes a container name, a directory and a git branch.

    It is validated in one place so the three cannot disagree, and the cases
    below are the ones that would otherwise produce an invalid branch ref or a
    surprising path.
    """

    def test_empty_is_refused(self):
        result = run("new", "")
        assert result.returncode != 0
        assert "required" in result.stderr

    def test_missing_is_refused(self):
        result = run("new")
        assert result.returncode != 0
        assert "required" in result.stderr

    def test_uppercase_and_underscores_are_refused(self):
        for name in ("Bad_Name", "UPPER", "has_underscore", "has space", "has/slash"):
            result = run("new", name)
            assert result.returncode != 0, f"{name!r} was accepted"
            assert "lowercase" in result.stderr

    def test_leading_or_trailing_hyphen_is_refused(self):
        for name in ("-leading", "trailing-"):
            result = run("new", name)
            assert result.returncode != 0, f"{name!r} was accepted"
            assert "hyphen" in result.stderr

    def test_a_good_name_gets_past_validation(self):
        """A well-formed name must fail for the *next* reason, not the name.

        Checked through `report`, which validates the name and then looks for a
        file — it creates nothing. An earlier version of this test called `new`,
        which was wrong twice over: a test of argument handling must not invoke a
        command that can create a container, and the assertion it made ("the run
        stops at the missing docker") silently depended on the machine having no
        container engine. It passed until an engine was installed.
        """
        result = run("report", "spec-01-contracts")
        assert result.returncode != 0
        assert "lowercase" not in result.stderr
        assert "hyphen" not in result.stderr
        # Past validation and into the real work: it is looking for the report.
        assert "report.md" in result.stderr

    def test_validation_happens_before_anything_is_created(self):
        """A rejected name must not reach the engine at all.

        `new` is the only command that creates something, so the guarantee is
        asserted where it matters: a bad name is refused by the argument check,
        never by something further down that might have had a side effect first.
        """
        result = run("new", "Bad_Name")
        assert result.returncode != 0
        assert "lowercase" in result.stderr
        assert "docker" not in result.stderr.lower()


class TestLogin:
    """Signing a vendor in is a one-time act, and it must stay one-time.

    The sign-in lands in a Docker named volume rather than the image or a bind
    mount, which is what makes it survive every container and every restart. It
    is also what keeps a live host credential out of a chamber that has network
    egress.
    """

    def test_a_missing_vendor_is_refused(self):
        result = run("login")
        assert result.returncode != 0
        assert "claude" in result.stderr and "codex" in result.stderr

    def test_an_unknown_vendor_is_refused(self):
        result = run("login", "gemini")
        assert result.returncode != 0
        assert "claude" in result.stderr and "codex" in result.stderr

    def test_the_script_names_no_credential_path_on_the_host(self):
        """The whole point is that no host credential is read or mounted.

        Asserted against the source, because the failure would be someone later
        'helpfully' bind-mounting `~/.codex` or reaching into the Keychain to
        save Tyrel a step. Both would put a live credential inside a chamber
        with network egress.
        """
        source = SCRIPT.read_text()
        for forbidden in (
            "~/.codex",
            "~/.claude",
            "$HOME/.codex",
            "$HOME/.claude",
            "security find-",
        ):
            assert forbidden not in source, f"launcher reaches for a host credential: {forbidden}"

    def test_auth_is_mounted_read_write(self):
        """Read-only would turn a one-time sign-in into a recurring one, because
        both CLIs refresh their own tokens and would have nowhere to write."""
        source = SCRIPT.read_text()
        for volume in ("AUTH_VOL_CLAUDE", "AUTH_VOL_CODEX"):
            assert f"${{{volume}}}:" in source
            assert f"${{{volume}}}:ro" not in source, f"{volume} is mounted read-only"

    def test_the_private_drawer_is_masked_inside_a_chamber(self):
        """`/src` read-only stops an agent changing this machine, not reading it.

        `private/` holds the notification bearer topic, and a chamber has open
        network egress, so a readable secret is a sendable one. The mount must be
        an empty tmpfs over that one path — not an exclusion from the bind, which
        Docker cannot express, and not deletion of the directory, which `/src`
        being read-only forbids anyway.
        """
        source = SCRIPT.read_text()
        assert "--tmpfs /src/private" in source, "the private drawer is exposed to every chamber"
        assert "/src/private:ro" in source, "the masking tmpfs is writable"


class TestDispatch:
    """Running an agent inside a chamber, against a brief written to a file."""

    def test_every_allowed_effort_gets_past_effort_validation(self):
        for effort in ("none", "minimal", "low", "medium", "high", "xhigh", "max"):
            result = run(
                "dispatch", "task-x", "claude", str(ROOT / "README.md"), "gpt-5.6-luna", effort
            )
            assert "not an allowed effort" not in result.stderr

    def test_a_missing_task_is_refused(self):
        result = run("dispatch")
        assert result.returncode != 0
        assert "required" in result.stderr

    def test_an_unknown_vendor_is_refused(self):
        # Arguments are now checked left to right and all of them before Docker is
        # touched, so this names the vendor rather than stopping at the chamber. The
        # previous ordering reported "chamber not running" for a command that was
        # never going to run whatever the chamber's state — true, and unhelpful.
        result = run("dispatch", "nosuchtask", "gemini", str(SCRIPT), "gpt-5.6-luna")
        assert result.returncode != 0
        assert "claude" in result.stderr and "codex" in result.stderr

    def test_the_brief_travels_as_a_file_never_as_an_argument(self):
        """A brief is prose a session wrote. Interpolated into a command line its
        punctuation becomes executable, so it is copied into the chamber's drawer
        and read there with `cat`."""
        source = SCRIPT.read_text()
        assert "cat /out/brief.md" in source
        assert "brief.md" in source

    def test_permission_skipping_is_confined_to_the_chamber(self):
        """`--dangerously-skip-permissions` is correct inside a container and
        nowhere else, because the container is the boundary and a prompt inside a
        detached one is a hang. This asserts it appears in exactly one runnable
        line, so it cannot drift into something that executes on the host.
        """
        lines = code_lines()
        carrying = [ln for ln in lines if "--dangerously-skip-permissions" in ln]
        assert len(carrying) == 1, f"expected one runnable use, found {len(carrying)}"
        index = lines.index(carrying[0])
        preceding = "\n".join(lines[:index])
        assert "docker exec" in preceding, "the flag is not inside a docker exec"

    def test_a_model_is_required(self):
        """An omitted model runs the vendor's default, and `codex doctor` reports that
        default is `gpt-5.6-sol` — the most expensive seat OpenAI sells. Every chamber
        would silently have been a flagship chamber and the tier table in
        `.claude/agents/README.md` would describe a choice nothing ever made."""
        result = run("dispatch", "task-x", "claude", str(ROOT / "README.md"))
        assert result.returncode != 0
        assert "needs a model" in result.stderr

    @pytest.mark.parametrize(
        ("model", "effort", "expected"),
        [
            ("-evil", "medium", "not a plain model name"),
            ("gpt-5.6-luna; touch PWNED", "medium", "not a plain model name"),
            ("gpt-5.6-luna", "bogus", "not an allowed effort"),
        ],
    )
    def test_the_model_and_effort_are_validated(self, model, effort, expected):
        """Validated rather than trusted, exactly as `operations/codex/seat.sh`
        validates the same fields. Both reach the container as environment variables
        and never as interpolated text, but a value beginning with `-` would still
        arrive at the CLI as a flag."""
        result = run("dispatch", "task-x", "claude", str(ROOT / "README.md"), model, effort)
        assert result.returncode != 0
        assert expected in result.stderr

    def test_validation_precedes_any_docker_call(self):
        """A typo in a model name should cost a line of output, not a container's
        startup and a confusing failure from a vendor CLI two layers down."""
        result = run("dispatch", "task-x", "claude", str(ROOT / "README.md"), "-evil")
        assert "docker" not in result.stderr.lower()

    def test_both_vendors_receive_model_and_effort_in_their_own_spelling(self):
        """The two CLIs spell effort differently and neither spelling is guessable.
        `claude` takes `--effort <level>`; `codex exec` has no effort flag at all and
        needs the config override `-c model_reasoning_effort=`, which is how
        `operations/codex/seat.sh` has always done it. Checked against `--help` on
        both rather than assumed."""
        joined = " ".join(code_lines())
        assert '--model "$AC_MODEL"' in joined and '--effort "$AC_EFFORT"' in joined
        assert '-m "$AC_MODEL"' in joined
        assert '-c "model_reasoning_effort=$AC_EFFORT"' in joined

    def test_the_model_travels_as_an_environment_variable(self):
        """Same reasoning as the brief travelling as a file: a value interpolated into
        a quoted command line brings its punctuation with it."""
        joined = " ".join(code_lines())
        assert joined.count('-e AC_MODEL="$model" -e AC_EFFORT="$effort"') == 2

    def test_the_codex_prompt_is_behind_an_end_of_options_marker(self):
        """A brief beginning with a dash must be read as the prompt, not as an
        unknown option. `seat.sh` does the same."""
        joined = " ".join(code_lines())
        assert '-- "$(cat /out/brief.md)"' in joined

    def test_codex_stdin_is_closed(self):
        """`codex exec` waits forever on an open stdin when nothing is attached,
        which inside a detached container is a dispatch that never returns and
        never says why. A known trap, recorded in this project's own notes.

        Continuations are joined before looking, because the invariant is that the
        *invocation* closes stdin and not that it fits on one physical line. Written
        the other way, this failed the moment a `--model` argument was added and the
        command wrapped — a test reporting a formatting change as a safety defect.
        """
        joined = " ".join(code_lines()).replace("\\ ", " ")
        carrying = [part for part in joined.split(";") if "codex exec" in part]
        assert len(carrying) == 1, f"expected one runnable use, found {len(carrying)}"
        assert "< /dev/null" in carrying[0]


def test_doctor_reports_sign_in_state_for_both_vendors():
    result = run("doctor")
    assert result.returncode == 0
    assert "auth claude" in result.stdout
    assert "auth codex" in result.stdout


def test_report_names_the_path_it_looked_for():
    """A missing report says where it looked, so the operator can go and see."""
    result = run("report", "no-such-task")
    assert result.returncode != 0
    assert "no-such-task" in result.stderr
    assert "report.md" in result.stderr


def test_output_root_is_inside_the_gitignored_workbench():
    """Nothing an agent produces may show up in `git status`.

    The drawer is under `workbench/`, which is gitignored, and this asserts the
    launcher agrees with that rather than trusting the comment.
    """
    result = run("doctor")
    assert "workbench/autoclave" in result.stdout


def test_the_brief_is_not_named_claude_md_on_the_host():
    """A `CLAUDE.md` here would be read by a host session working in this tree
    and would tell it, falsely, that it is inside a container. The Dockerfile
    renames the file on the way into the image, which is the only place the
    brief's claims are true."""
    directory = ROOT / "operations" / "autoclave"
    assert (directory / "agent-brief.md").is_file()
    assert not (directory / "CLAUDE.md").exists()


def test_dockerignore_denies_everything_before_admitting_anything():
    """The deny-all form is load-bearing: `private/` holds the notification
    topic, and an exclusion list goes stale the day a new drawer is added."""
    lines = [
        line.strip()
        for line in (ROOT / ".dockerignore").read_text().splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
    assert lines[0] == "*", "the first rule must deny everything"
    assert all(line.startswith("!") for line in lines[1:]), (
        "after the deny-all, every rule must be a re-admission"
    )
    admitted = {line[1:] for line in lines[1:]}
    assert "operations/autoclave/agent-brief.md" in admitted
    assert not any(entry.startswith("private") for entry in admitted)
