"""Model-free RunTree cardinality exercise for the R7b pre-production bench."""

from __future__ import annotations

import shutil
import time
from pathlib import Path
from typing import Any, Final

from common.contracts.canonical import canonical_bytes, digest_bytes
from common.contracts.envelope import build_envelope
from common.contracts.identities import artifact_id, page_id
from common.contracts.stages import DESIGNATOR
from common.runtree.store import RUN_FILE, PublishResult, RunTree

_SEALED_SHARDS: Final = 10
_SEALED_PAGES_PER_SHARD: Final = 1_000
SHARDS: Final = _SEALED_SHARDS
PAGES_PER_SHARD: Final = _SEALED_PAGES_PER_SHARD
CONFIG_DIGEST = digest_bytes(b"r7b-runtree-scale-v1")
_CENSUS_FILE: Final = "aggregate-census.json"


def _source(shard: int, ordinal: int) -> dict[str, object]:
    content_digest = digest_bytes(f"r7b-scale-page:{shard}:{ordinal}".encode())
    return {
        "relative_path": f"synthetic/{shard:02d}/{ordinal:04d}.png",
        "sha256": content_digest,
        "ordinal": ordinal,
    }


def _proposal(run_id: str, source: dict[str, object]) -> dict[str, object]:
    page = page_id(source["sha256"], source["ordinal"])
    return build_envelope(
        run_id=run_id,
        artifact_id=artifact_id(DESIGNATOR, "proposal", page),
        subject_id=page,
        stage=DESIGNATOR,
        kind="proposal",
        outcome="proposed",
        config_digest=CONFIG_DIGEST,
        adapter_revision="r7b-scale-synthetic-v1",
        inputs=[],
        payload={"proposals": 1},
    )


def run_scale(
    root: Path,
    *,
    shards: int = _SEALED_SHARDS,
    pages_per_shard: int = _SEALED_PAGES_PER_SHARD,
    allow_undersized_smoke: bool = False,
) -> dict[str, Any]:
    """Create, resume, manifest, and census ten bounded synthetic RunTrees.

    The generated bytes are provenance-shaped but contain neither model inputs
    nor model outputs.  Callers must supply an empty/nonexistent target; this
    prevents a benchmark from silently mixing its census with another run.
    Positive undersized dimensions require explicit smoke opt-in and produce a
    smoke-only state that cannot be mistaken for the sealed measurement.
    """
    is_sealed = shards == _SEALED_SHARDS and pages_per_shard == _SEALED_PAGES_PER_SHARD
    is_undersized = (
        0 < shards <= _SEALED_SHARDS
        and 0 < pages_per_shard <= _SEALED_PAGES_PER_SHARD
        and not is_sealed
    )
    if not is_sealed and not (allow_undersized_smoke and is_undersized):
        raise ValueError(
            "the R7b scale bench is fixed at 10 shards of 1,000 pages; "
            "pass allow_undersized_smoke=True only for a positive undersized smoke run"
        )
    if root.exists():
        raise FileExistsError(f"scale root already exists: {root}")
    started = time.perf_counter()
    state = "measured" if is_sealed else "smoke-undersized"
    manifests: list[dict[str, object]] = []
    expected_artifact_count = shards * pages_per_shard
    artifact_count = 0
    missing_pages: list[tuple[int, int]] = []
    root.mkdir(parents=True)
    create_started = time.perf_counter()
    for shard in range(1, shards + 1):
        run_id = f"bench-scale-{shard:02d}"
        source = [_source(shard, ordinal) for ordinal in range(1, pages_per_shard + 1)]
        tree = RunTree.create(
            root,
            run_id,
            source_manifest=source,
            config_digest=CONFIG_DIGEST,
            adapter_recipes={"designator": "r7b-scale-synthetic-v1"},
            witness_chairs=[],
        )
        for page in source:
            publication = tree.publish_artifact(_proposal(run_id, page))
            if isinstance(publication, PublishResult):
                artifact_count += 1
            else:
                missing_pages.append((shard, int(page["ordinal"])))
        manifests.append(tree.build_manifest(DESIGNATOR))
    create_seconds = time.perf_counter() - create_started
    if artifact_count != expected_artifact_count:
        raise RuntimeError(
            f"scale bench published {artifact_count} artifacts; "
            f"expected {expected_artifact_count}; a partial publication cannot "
            f"produce a census or result; non-receipted pages: {missing_pages}"
        )
    resume_started = time.perf_counter()
    for shard in range(1, shards + 1):
        run_id = f"bench-scale-{shard:02d}"
        source = [_source(shard, ordinal) for ordinal in range(1, pages_per_shard + 1)]
        authority = root / run_id / RUN_FILE
        if not authority.is_file():
            raise FileNotFoundError(
                f"scale resume requires existing RunTree authority {RUN_FILE}; "
                f"missing regular file: {authority}"
            )
        RunTree.create(
            root,
            run_id,
            source_manifest=source,
            config_digest=CONFIG_DIGEST,
            adapter_recipes={"designator": "r7b-scale-synthetic-v1"},
            witness_chairs=[],
        )
    resume_seconds = time.perf_counter() - resume_started
    export_started = time.perf_counter()
    census = {
        "schema": "r7b-runtree-scale-census.v1",
        "state": state,
        "shards": shards,
        "pages_per_shard": pages_per_shard,
        "runs": manifests,
        "artifact_count": artifact_count,
    }
    (root / _CENSUS_FILE).write_bytes(canonical_bytes(census))
    export_seconds = time.perf_counter() - export_started
    disk_bytes = sum(path.stat().st_size for path in root.rglob("*") if path.is_file())
    inodes = sum(1 for _ in root.rglob("*"))
    return {
        "schema": "r7b-runtree-scale-result.v1",
        "state": state,
        "shards": shards,
        "pages_per_shard": pages_per_shard,
        "artifact_count": artifact_count,
        "create_seconds": create_seconds,
        "resume_seconds": resume_seconds,
        "manifest_export_seconds": export_seconds,
        "wall_seconds": time.perf_counter() - started,
        "disk_bytes": disk_bytes,
        "inodes": inodes,
    }


def cleanup_scale(root: Path) -> None:
    """Remove a known scale scratch directory after its result is recorded."""
    marker = root / _CENSUS_FILE
    if not marker.is_file():
        raise FileNotFoundError(
            f"scale cleanup requires the {_CENSUS_FILE} marker; missing regular file: {marker}"
        )
    shutil.rmtree(root)
