"""Model-free RunTree cardinality exercise for the R7b pre-production bench."""

from __future__ import annotations

import shutil
import time
from pathlib import Path
from typing import Any

from common.contracts.canonical import canonical_bytes, digest_bytes
from common.contracts.envelope import build_envelope
from common.contracts.identities import artifact_id, page_id
from common.contracts.stages import DESIGNATOR
from common.runtree.store import RunTree

SHARDS = 10
PAGES_PER_SHARD = 1_000
CONFIG_DIGEST = digest_bytes(b"r7b-runtree-scale-v1")


def _source(shard: int, ordinal: int) -> dict[str, object]:
    content_digest = digest_bytes(f"r7b-scale-page:{shard}:{ordinal}".encode())
    return {
        "relative_path": f"synthetic/{shard:02d}/{ordinal:04d}.png",
        "sha256": content_digest,
        "ordinal": ordinal,
    }


def _proposal(run_id: str, source: dict[str, object]) -> dict[str, object]:
    page = page_id(source["sha256"], source["ordinal"])
    return build_envelope(
        run_id=run_id,
        artifact_id=artifact_id(DESIGNATOR, "proposal", page),
        subject_id=page,
        stage=DESIGNATOR,
        kind="proposal",
        outcome="proposed",
        config_digest=CONFIG_DIGEST,
        adapter_revision="r7b-scale-synthetic-v1",
        inputs=[],
        payload={"proposals": 1},
    )


def run_scale(
    root: Path, *, shards: int = SHARDS, pages_per_shard: int = PAGES_PER_SHARD
) -> dict[str, Any]:
    """Create, resume, manifest, and census ten bounded synthetic RunTrees.

    The generated bytes are provenance-shaped but contain neither model inputs
    nor model outputs.  Callers must supply an empty/nonexistent target; this
    prevents a benchmark from silently mixing its census with another run.
    """
    if shards != SHARDS or pages_per_shard != PAGES_PER_SHARD:
        raise ValueError("the R7b scale bench is fixed at 10 shards of 1,000 pages")
    if root.exists():
        raise FileExistsError(f"scale root already exists: {root}")
    started = time.perf_counter()
    manifests: list[dict[str, object]] = []
    root.mkdir(parents=True)
    create_started = time.perf_counter()
    for shard in range(1, shards + 1):
        run_id = f"bench-scale-{shard:02d}"
        source = [_source(shard, ordinal) for ordinal in range(1, pages_per_shard + 1)]
        tree = RunTree.create(
            root,
            run_id,
            source_manifest=source,
            config_digest=CONFIG_DIGEST,
            adapter_recipes={"designator": "r7b-scale-synthetic-v1"},
            witness_chairs=[],
        )
        for page in source:
            tree.publish_artifact(_proposal(run_id, page))
        manifests.append(tree.build_manifest(DESIGNATOR))
    create_seconds = time.perf_counter() - create_started
    resume_started = time.perf_counter()
    for shard in range(1, shards + 1):
        run_id = f"bench-scale-{shard:02d}"
        source = [_source(shard, ordinal) for ordinal in range(1, pages_per_shard + 1)]
        RunTree.create(
            root,
            run_id,
            source_manifest=source,
            config_digest=CONFIG_DIGEST,
            adapter_recipes={"designator": "r7b-scale-synthetic-v1"},
            witness_chairs=[],
        )
    resume_seconds = time.perf_counter() - resume_started
    export_started = time.perf_counter()
    census = {
        "schema": "r7b-runtree-scale-census.v1",
        "runs": manifests,
        "artifact_count": shards * pages_per_shard,
    }
    (root / "aggregate-census.json").write_bytes(canonical_bytes(census))
    export_seconds = time.perf_counter() - export_started
    disk_bytes = sum(path.stat().st_size for path in root.rglob("*") if path.is_file())
    inodes = sum(1 for _ in root.rglob("*"))
    return {
        "schema": "r7b-runtree-scale-result.v1",
        "state": "measured",
        "shards": shards,
        "pages_per_shard": pages_per_shard,
        "artifact_count": shards * pages_per_shard,
        "create_seconds": create_seconds,
        "resume_seconds": resume_seconds,
        "manifest_export_seconds": export_seconds,
        "wall_seconds": time.perf_counter() - started,
        "disk_bytes": disk_bytes,
        "inodes": inodes,
    }


def cleanup_scale(root: Path) -> None:
    """Remove a known scale scratch directory after its result is recorded."""
    shutil.rmtree(root)
