"""Model-free RunTree cardinality exercise for the R7b pre-production bench."""

from __future__ import annotations

import json
import re
import shutil
import stat
import time
from pathlib import Path
from typing import Any, Final

from common.contracts.canonical import SCHEMA_LABEL, canonical_bytes, digest_bytes
from common.contracts.envelope import build_envelope
from common.contracts.identities import artifact_id, page_id
from common.contracts.stages import DESIGNATOR
from common.runtree.store import RUN_FILE, PublishResult, RunTree

_SEALED_SHARDS: Final = 10
_SEALED_PAGES_PER_SHARD: Final = 1_000
SHARDS: Final = _SEALED_SHARDS
PAGES_PER_SHARD: Final = _SEALED_PAGES_PER_SHARD
CONFIG_DIGEST = digest_bytes(b"r7b-runtree-scale-v1")
_CENSUS_FILE: Final = "aggregate-census.json"
_CENSUS_SCHEMA: Final = "r7b-runtree-scale-census.v1"
_RESULT_FILE: Final = "scale-result.json"
_RESULT_SCHEMA: Final = "r7b-runtree-scale-result.v1"
_RESULT_FIELDS: Final = {
    "schema",
    "state",
    "shards",
    "pages_per_shard",
    "artifact_count",
    "create_seconds",
    "resume_seconds",
    "manifest_export_seconds",
    "wall_seconds",
    "disk_bytes",
    "inodes",
}
_SECONDS_FIELDS: Final = (
    "create_seconds",
    "resume_seconds",
    "manifest_export_seconds",
    "wall_seconds",
)
_DECIMAL_SECONDS_PATTERN: Final = re.compile(r"[0-9]+\.[0-9]{9}")


def _decimal_seconds(nanoseconds: int) -> str:
    """Represent an observed duration exactly in canonical-JSON-compatible seconds."""
    whole, fractional = divmod(nanoseconds, 1_000_000_000)
    return f"{whole}.{fractional:09d}"


def _tree_storage(root: Path) -> tuple[int, int]:
    entries = list(root.rglob("*"))
    disk_bytes = sum(path.stat().st_size for path in entries if path.is_file())
    return disk_bytes, len(entries)


def _source(shard: int, ordinal: int) -> dict[str, object]:
    content_digest = digest_bytes(f"r7b-scale-page:{shard}:{ordinal}".encode())
    return {
        "relative_path": f"synthetic/{shard:02d}/{ordinal:04d}.png",
        "sha256": content_digest,
        "ordinal": ordinal,
    }


def _proposal(run_id: str, source: dict[str, object]) -> dict[str, object]:
    page = page_id(source["sha256"], source["ordinal"])
    return build_envelope(
        run_id=run_id,
        artifact_id=artifact_id(DESIGNATOR, "proposal", page),
        subject_id=page,
        stage=DESIGNATOR,
        kind="proposal",
        outcome="proposed",
        config_digest=CONFIG_DIGEST,
        adapter_revision="r7b-scale-synthetic-v1",
        inputs=[],
        payload={"proposals": 1},
    )


def run_scale(
    root: Path,
    *,
    shards: int = _SEALED_SHARDS,
    pages_per_shard: int = _SEALED_PAGES_PER_SHARD,
    allow_undersized_smoke: bool = False,
) -> dict[str, Any]:
    """Create, resume, manifest, and census ten bounded synthetic RunTrees.

    The generated bytes are provenance-shaped but contain neither model inputs
    nor model outputs.  Callers must supply an empty/nonexistent target; this
    prevents a benchmark from silently mixing its census with another run.
    Positive undersized dimensions require explicit smoke opt-in and produce a
    smoke-only state that cannot be mistaken for the sealed measurement.
    """
    is_sealed = shards == _SEALED_SHARDS and pages_per_shard == _SEALED_PAGES_PER_SHARD
    is_undersized = (
        0 < shards <= _SEALED_SHARDS
        and 0 < pages_per_shard <= _SEALED_PAGES_PER_SHARD
        and not is_sealed
    )
    if not is_sealed and not (allow_undersized_smoke and is_undersized):
        raise ValueError(
            "the R7b scale bench is fixed at 10 shards of 1,000 pages; "
            "pass allow_undersized_smoke=True only for a positive undersized smoke run"
        )
    if root.exists():
        raise FileExistsError(f"scale root already exists: {root}")
    started = time.perf_counter_ns()
    state = "measured" if is_sealed else "smoke-undersized"
    manifests: list[dict[str, object]] = []
    expected_artifact_count = shards * pages_per_shard
    artifact_count = 0
    missing_pages: list[tuple[int, int]] = []
    root.mkdir(parents=True)
    create_started = time.perf_counter_ns()
    for shard in range(1, shards + 1):
        run_id = f"bench-scale-{shard:02d}"
        source = [_source(shard, ordinal) for ordinal in range(1, pages_per_shard + 1)]
        tree = RunTree.create(
            root,
            run_id,
            source_manifest=source,
            config_digest=CONFIG_DIGEST,
            adapter_recipes={"designator": "r7b-scale-synthetic-v1"},
            witness_chairs=[],
        )
        for page in source:
            publication = tree.publish_artifact(_proposal(run_id, page))
            if isinstance(publication, PublishResult):
                artifact_count += 1
            else:
                missing_pages.append((shard, int(page["ordinal"])))
        manifests.append(tree.build_manifest(DESIGNATOR))
    create_seconds = _decimal_seconds(time.perf_counter_ns() - create_started)
    if artifact_count != expected_artifact_count:
        raise RuntimeError(
            f"scale bench published {artifact_count} artifacts; "
            f"expected {expected_artifact_count}; a partial publication cannot "
            f"produce a census or result; non-receipted pages: {missing_pages}"
        )
    resume_started = time.perf_counter_ns()
    for shard in range(1, shards + 1):
        run_id = f"bench-scale-{shard:02d}"
        source = [_source(shard, ordinal) for ordinal in range(1, pages_per_shard + 1)]
        authority = root / run_id / RUN_FILE
        if not authority.is_file():
            raise FileNotFoundError(
                f"scale resume requires existing RunTree authority {RUN_FILE}; "
                f"missing regular file: {authority}"
            )
        RunTree.create(
            root,
            run_id,
            source_manifest=source,
            config_digest=CONFIG_DIGEST,
            adapter_recipes={"designator": "r7b-scale-synthetic-v1"},
            witness_chairs=[],
        )
    resume_seconds = _decimal_seconds(time.perf_counter_ns() - resume_started)
    export_started = time.perf_counter_ns()
    census = {
        "schema": _CENSUS_SCHEMA,
        "state": state,
        "shards": shards,
        "pages_per_shard": pages_per_shard,
        "runs": manifests,
        "artifact_count": artifact_count,
    }
    (root / _CENSUS_FILE).write_bytes(canonical_bytes(census))
    export_seconds = _decimal_seconds(time.perf_counter_ns() - export_started)
    pre_result_disk_bytes, pre_result_inodes = _tree_storage(root)
    result = {
        "schema": _RESULT_SCHEMA,
        "state": state,
        "shards": shards,
        "pages_per_shard": pages_per_shard,
        "artifact_count": artifact_count,
        "create_seconds": create_seconds,
        "resume_seconds": resume_seconds,
        "manifest_export_seconds": export_seconds,
        "wall_seconds": _decimal_seconds(time.perf_counter_ns() - started),
        "disk_bytes": pre_result_disk_bytes,
        "inodes": pre_result_inodes + 1,
    }
    # The result is part of the scratch tree whose storage it reports. Its byte
    # count reaches a fixed point once the digit width of disk_bytes stops moving.
    while True:
        result_bytes = canonical_bytes(result)
        complete_disk_bytes = pre_result_disk_bytes + len(result_bytes)
        if result["disk_bytes"] == complete_disk_bytes:
            break
        result["disk_bytes"] = complete_disk_bytes
    (root / _RESULT_FILE).write_bytes(result_bytes)
    return result


def _validate_scale_census(census: Any) -> list[str]:
    expected_fields = {
        "schema",
        "state",
        "shards",
        "pages_per_shard",
        "runs",
        "artifact_count",
    }
    if not isinstance(census, dict) or set(census) != expected_fields:
        raise ValueError("scale cleanup marker is not a valid R7b scale census: wrong fields")
    shards = census["shards"]
    pages_per_shard = census["pages_per_shard"]
    if (
        not isinstance(shards, int)
        or isinstance(shards, bool)
        or not 0 < shards <= _SEALED_SHARDS
        or not isinstance(pages_per_shard, int)
        or isinstance(pages_per_shard, bool)
        or not 0 < pages_per_shard <= _SEALED_PAGES_PER_SHARD
    ):
        raise ValueError("scale cleanup marker is not a valid R7b scale census: invalid dimensions")
    expected_state = (
        "measured"
        if shards == _SEALED_SHARDS and pages_per_shard == _SEALED_PAGES_PER_SHARD
        else "smoke-undersized"
    )
    if census["schema"] != _CENSUS_SCHEMA or census["state"] != expected_state:
        raise ValueError(
            "scale cleanup marker is not a valid R7b scale census: schema or state mismatch"
        )
    artifact_count = census["artifact_count"]
    if (
        not isinstance(artifact_count, int)
        or isinstance(artifact_count, bool)
        or artifact_count != shards * pages_per_shard
    ):
        raise ValueError(
            "scale cleanup marker is not a valid R7b scale census: cardinality mismatch"
        )
    runs = census["runs"]
    if not isinstance(runs, list) or len(runs) != shards:
        raise ValueError("scale cleanup marker is not a valid R7b scale census: run count mismatch")
    expected_run_ids = [f"bench-scale-{shard:02d}" for shard in range(1, shards + 1)]
    manifest_fields = {"schema", "run_id", "stage", "artifacts", "blobs"}
    for manifest, expected_run_id in zip(runs, expected_run_ids, strict=True):
        if (
            not isinstance(manifest, dict)
            or set(manifest) != manifest_fields
            or manifest["schema"] != SCHEMA_LABEL
            or manifest["run_id"] != expected_run_id
            or manifest["stage"] != DESIGNATOR
            or not isinstance(manifest["artifacts"], list)
            or len(manifest["artifacts"]) != pages_per_shard
            or manifest["blobs"] != []
        ):
            raise ValueError(
                "scale cleanup marker is not a valid R7b scale census: run manifest mismatch"
            )
    return expected_run_ids


def _is_regular_nonsymlink_file(path: Path) -> bool:
    try:
        return stat.S_ISREG(path.lstat().st_mode)
    except OSError:
        return False


def _validate_scale_result(result: Any, census: dict[str, Any], root: Path) -> None:
    if not isinstance(result, dict) or set(result) != _RESULT_FIELDS:
        raise ValueError(f"scale cleanup {_RESULT_FILE} has the wrong fields")
    if result["schema"] != _RESULT_SCHEMA:
        raise ValueError(f"scale cleanup {_RESULT_FILE} has a schema mismatch")
    for field in ("state", "shards", "pages_per_shard", "artifact_count"):
        if type(result[field]) is not type(census[field]) or result[field] != census[field]:
            raise ValueError(f"scale cleanup {_RESULT_FILE} has a {field} mismatch with the census")
    for field in _SECONDS_FIELDS:
        value = result[field]
        if not isinstance(value, str) or _DECIMAL_SECONDS_PATTERN.fullmatch(value) is None:
            raise ValueError(f"scale cleanup {_RESULT_FILE} has an invalid {field}")
    for field in ("disk_bytes", "inodes"):
        value = result[field]
        if type(value) is not int or value < 0:
            raise ValueError(f"scale cleanup {_RESULT_FILE} has an invalid {field}")
    tree_disk_bytes, tree_inodes = _tree_storage(root)
    for field, observed in (("disk_bytes", tree_disk_bytes), ("inodes", tree_inodes)):
        if result[field] != observed:
            raise ValueError(f"scale cleanup {_RESULT_FILE} has {field} mismatch with the tree")


def cleanup_scale(root: Path) -> None:
    """Remove a validated scale scratch directory after its result is recorded."""
    marker = root / _CENSUS_FILE
    if not _is_regular_nonsymlink_file(marker):
        raise FileNotFoundError(
            f"scale cleanup requires the {_CENSUS_FILE} marker as a regular non-symlink file: "
            f"{marker}"
        )
    try:
        census = json.loads(marker.read_bytes())
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise ValueError(
            "scale cleanup marker is not a valid R7b scale census: unreadable JSON"
        ) from error
    run_ids = _validate_scale_census(census)
    result_path = root / _RESULT_FILE
    if not _is_regular_nonsymlink_file(result_path):
        raise FileNotFoundError(
            f"scale cleanup requires {_RESULT_FILE} as a regular non-symlink file: {result_path}"
        )
    try:
        result_bytes = result_path.read_bytes()
        result = json.loads(result_bytes)
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise ValueError(f"scale cleanup {_RESULT_FILE} is unreadable JSON") from error
    try:
        canonical_result_bytes = canonical_bytes(result)
    except (TypeError, ValueError, RecursionError) as error:
        raise ValueError(f"scale cleanup {_RESULT_FILE} is not canonical JSON") from error
    if result_bytes != canonical_result_bytes:
        raise ValueError(f"scale cleanup {_RESULT_FILE} is not canonical bytes")
    for run_id in run_ids:
        authority = root / run_id / RUN_FILE
        if not _is_regular_nonsymlink_file(authority):
            raise FileNotFoundError(
                "scale cleanup census names a run without its RunTree authority; "
                f"expected a regular non-symlink file: {authority}"
            )
    _validate_scale_result(result, census, root)
    shutil.rmtree(root)
