"""Boot B -- the first real pipeline run on a pod, rendered as a request.

`operations/pod/README.md`'s boot plan splits the first live demonstration in
two: Boot A is the drill (`bootstrap_main --hold-only`, an immediate close, the
four facts no offline test can buy), and **Boot B is the real thing** -- the
full bootstrap, the preflight, and one pipeline run over the volume through
`pod_run`.

This module renders Boot B's request the way `boot_a_request.py` renders the
drill's: from the sealed spend policy and the reviewed placement table, so what
Tyrel reads is derived from the numbers the launch will enforce. **It authorizes
nothing.**

**It is generated by the code that validates it, and that is the point of the
file.** Boot B's `docker_start_cmd` is the only shape in this tree that nests
*two* argv halves -- `pod_run`'s own, then `bootstrap_main`'s after a literal
`--` -- and until a pre-launch review composed one by hand, nothing in the
repository ever had. `PodCreateRequest`'s money-path validation counted the two
halves' `--report-path` values together and refused every possible Boot B
before any preview, lease or provider call, while the offline suite stayed
green over a gap no test reached. So this renderer does not print JSON and hope:
:func:`validated_pod_request` builds a real :class:`PodCreateRequest` from the
rendered fields (with specimen values standing in for what only Tyrel supplies)
and re-renders the *sealed* argv a launch would produce, so a request shape the
launcher would refuse cannot be rendered here at all.

What the rendered request deliberately does **not** carry:

* no `--transfer-target-factory` and no bootstrap `--submission-manifest`. Boot
  B *consumes* a submission that `verbatus upload` already put on the volume;
  the pod has nothing to send back, and TRANSFER records "nothing to transfer".
  `pod_run`'s own `--submission-manifest` -- a different flag, on the run half
  -- names the ledger the run reads.
* no launch token in any report or journal name. `launch._bind_report_path_to_launch`
  folds the sealed token into the timer's `--report-path` and into the nested
  argv's `--report-path` and `--journal` at create time; a token cannot be
  pre-written because it is minted inside `create`.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from decimal import ROUND_UP, Decimal
from pathlib import Path
from typing import Sequence

from .boot_a_request import BOOT_A_VOLUME_MOUNT_PATH, _validate_hard_deadline, cheapest_card
from .models import PodCreateRequest, SpendRefusal, require_utc
from .preflight import CardProfile, PlacementTable, load_placement_table
from .spend import SpendPolicy, load_spend_policy

UTC = timezone.utc

BOOT_B_VOLUME_MOUNT_PATH = BOOT_A_VOLUME_MOUNT_PATH
"""One mount path for both boots: `config/data_handling_policy.json` lists it as
an approved storage root, and `pod_run` refuses a volume mount that is this exact
path without anything actually mounted there."""

BOOT_B_REPOSITORY_PATH = "/opt/verbatus"
"""Where the image's checkout lives, on container-local disk.

Not on the volume: the bootstrap requires the lockfile and every config inside
`--repository`, and the volume's own paths are separately constrained. The image
contract in `operations/pod/README.md` says what has to be true of this
directory -- an `origin` remote whose credentials a HOME-less git can see, and a
pre-built `.venv` the pod's primary process is started from.
"""

BOOT_B_RUN_ID = "<fill in by hand: this run's id>"
BOOT_B_COMMIT = "<fill in by hand: the same commit as repository_commit above>"
_UNSUPPLIED = "<not yet supplied>"

# Specimens used only to prove the rendered shape validates offline. They are
# never printed and never sent: a real launch replaces each of them with the
# value Tyrel supplies.
_SPECIMEN_IMAGE = "registry.example/verbatus@sha256:" + "0" * 64
_SPECIMEN_VOLUME_ID = "specimen-volume-id"
_SPECIMEN_COMMIT = "0" * 40
_SPECIMEN_RUN_ID = "boot-b-specimen"


@dataclass(frozen=True, slots=True)
class BootBRequest:
    """What was rendered, and whether it is a request at all."""

    text: str
    refused: bool
    card: CardProfile | None
    hard_lifetime_seconds: int | None
    estimated_pod_cost_usd: Decimal | None


def render_boot_b_request(
    policy: SpendPolicy,
    placement: PlacementTable,
    *,
    image: str | None = None,
    volume_id: str | None = None,
    repository_commit: str | None = None,
    run_id: str | None = None,
    gpu_type: str | None = None,
    hard_deadline: str | None = None,
    now: datetime | None = None,
) -> BootBRequest:
    """Render the real-run request, or a refusal when the policy cannot back one."""

    if not policy.configured:
        return BootBRequest(_refusal(), True, None, None, None)
    if (
        policy.hard_lifetime_seconds is None
        or policy.max_hourly_usd is None
        or policy.max_estimated_metered_cost_usd is None
    ):
        raise ValueError(
            "a configured spend policy must name hard_lifetime_seconds, max_hourly_usd and "
            "max_estimated_metered_cost_usd; the Boot B request cannot be rendered against a "
            "ceiling that is not there"
        )
    card = _card(placement, gpu_type)
    lifetime = policy.hard_lifetime_seconds
    pod_cost = _cents(card.hourly_usd * Decimal(lifetime) / Decimal(3600))
    obstacles: list[str] = []
    if card.hourly_usd > policy.max_hourly_usd:
        obstacles.append(
            f"the selected card bills ${card.hourly_usd}/h, above max_hourly_usd "
            f"${policy.max_hourly_usd}; the preview will refuse this run"
        )
    if pod_cost > policy.max_estimated_metered_cost_usd:
        obstacles.append(
            f"a full lifetime on this card costs ${pod_cost}, above "
            f"max_estimated_metered_cost_usd ${policy.max_estimated_metered_cost_usd}; the "
            "preview will refuse this run"
        )
    if hard_deadline is not None:
        _validate_hard_deadline(
            hard_deadline, now=now or datetime.now(UTC), lifetime_seconds=lifetime
        )
    request = pod_request(
        card,
        image=image,
        volume_id=volume_id,
        repository_commit=repository_commit,
        run_id=run_id,
        hard_deadline=hard_deadline,
    )
    # Rendered and then proven, in that order, on every call: what is printed
    # below is a shape the launcher's own validation has just accepted.
    validated_pod_request(request)
    text = _render(policy, card, lifetime, pod_cost, obstacles, request)
    return BootBRequest(text, False, card, lifetime, pod_cost)


def _card(placement: PlacementTable, gpu_type: str | None) -> CardProfile:
    if gpu_type is None:
        return cheapest_card(placement)
    for profile in placement.card_profiles:
        if profile.gpu_type_id == gpu_type:
            return profile
    reviewed = ", ".join(sorted(profile.gpu_type_id for profile in placement.card_profiles))
    raise ValueError(
        f"{gpu_type!r} is not a reviewed card in the placement table; the reviewed rows are "
        f"{reviewed}. A card the table has not reviewed has no price the ceilings can be "
        "measured against"
    )


def pod_request(
    card: CardProfile,
    *,
    image: str | None,
    volume_id: str | None,
    repository_commit: str | None,
    run_id: str | None,
    hard_deadline: str | None = None,
    volume_mount_path: str = BOOT_B_VOLUME_MOUNT_PATH,
    repository: str = BOOT_B_REPOSITORY_PATH,
) -> dict[str, object]:
    """The `cli.py create --request` JSON for the real run, placeholders where Tyrel decides.

    The nested command is a complete ``pod_run`` argv: the run half, a literal
    ``--``, then a complete ``bootstrap_main`` argv. Both halves name their own
    ``--report-path`` and they are two different files, which is what
    ``pod_run.resolve_run_plan`` requires and what the create gate now allows.
    """

    run_half = [
        "python",
        "-m",
        "operations.pod.pod_run",
        "--report-path",
        f"{volume_mount_path}/pod-run-report.json",
        "--run-id",
        run_id or BOOT_B_RUN_ID,
        "--run-root",
        f"{volume_mount_path}/runs",
        "--submission-folder",
        f"{volume_mount_path}/submission",
        # The run half's manifest: the ledger `verbatus upload` wrote beside the
        # submission on the volume, which this run reads. The bootstrap half
        # names no manifest of its own -- this pod sends nothing anywhere.
        "--submission-manifest",
        f"{volume_mount_path}/submission/manifest.json",
    ]
    bootstrap_half = [
        "--volume-mount-path",
        volume_mount_path,
        "--report-path",
        f"{volume_mount_path}/bootstrap-report.json",
        "--repository",
        repository,
        # The commit appears twice in a Boot B request -- once as the request's
        # own `repository_commit`, which the launch seals and the runtime
        # contract checks, and once inside the bootstrap argv, which is what
        # actually gets checked out. They must be the same string, so the
        # placeholder here says so rather than printing a plausible-looking
        # SHA nobody meant.
        "--repository-commit",
        repository_commit or BOOT_B_COMMIT,
        "--lockfile",
        f"{repository}/uv.lock",
        "--journal",
        f"{volume_mount_path}/bootstrap-journal.json",
        "--store-root",
        f"{volume_mount_path}/model-store",
        "--models-config",
        f"{repository}/config/models.toml",
        "--placement-config",
        f"{repository}/config/pod_placement.toml",
    ]
    nested = [*run_half, "--", *bootstrap_half]
    return {
        "name": "boot-b-run",
        "gpu_type": card.gpu_type_id,
        "image": image or _UNSUPPLIED,
        "volume_id": volume_id or _UNSUPPLIED,
        "volume_mount_path": volume_mount_path,
        "docker_start_cmd": [
            "python",
            "-m",
            "operations.pod.pod_timer",
            "--timer-factory",
            "operations.pod.provider_runpod:timer_context_from_environment",
            "--bootstrap-command-json",
            json.dumps(nested),
            "--report-path",
            f"{volume_mount_path}/pod-runtime-report.json",
        ],
        "hard_deadline": hard_deadline
        or "<fill in by hand: an RFC3339 UTC timestamp at least this run's own "
        "hard_lifetime_seconds past now -- create will not accept this file until you do>",
        "repository_commit": repository_commit or _UNSUPPLIED,
        # Stated rather than left to the provider's default: the bootstrap
        # installs the serving stack onto container-local disk twice over.
        # `models.DEFAULT_CONTAINER_DISK_GB` carries the arithmetic.
        "container_disk_gb": 60,
        "metadata": {"VERBATUS_BILLING_CUTOFF_MARGIN_SECONDS": "<the sealed policy value>"},
    }


def validated_pod_request(request: dict[str, object]) -> PodCreateRequest:
    """Build the real request object this JSON describes, with specimens filled in.

    Every refusal ``cli._request`` and ``PodCreateRequest`` can make about this
    shape is made here, offline, at render time -- so the Boot B request cannot
    be published in a shape the money path would reject. Only the fields Tyrel
    supplies are substituted, and only when they are still placeholders; the
    argv, the mount path, the container disk and the timer wiring are exactly
    what is printed.
    """

    fields = dict(request)
    if not _is_supplied(fields.get("image")):
        fields["image"] = _SPECIMEN_IMAGE
    if not _is_supplied(fields.get("volume_id")):
        fields["volume_id"] = _SPECIMEN_VOLUME_ID
    if not _is_supplied(fields.get("repository_commit")):
        fields["repository_commit"] = _SPECIMEN_COMMIT
    command = list(fields["docker_start_cmd"])  # type: ignore[arg-type]
    for placeholder, specimen in (
        (BOOT_B_RUN_ID, _SPECIMEN_RUN_ID),
        (BOOT_B_COMMIT, _SPECIMEN_COMMIT),
    ):
        command = [part.replace(placeholder, specimen) for part in command]
    deadline = fields.get("hard_deadline")
    if not isinstance(deadline, str) or deadline.startswith("<"):
        parsed = datetime.now(UTC).replace(microsecond=0)
    else:
        parsed = require_utc(
            datetime.fromisoformat(deadline.replace("Z", "+00:00")), "hard_deadline"
        )
    return PodCreateRequest(
        name=str(fields["name"]),
        gpu_type=str(fields["gpu_type"]),
        image=str(fields["image"]),
        volume_id=str(fields["volume_id"]),
        volume_mount_path=str(fields["volume_mount_path"]),
        docker_start_cmd=tuple(command),
        hard_deadline=parsed,
        repository_commit=str(fields["repository_commit"]),
        container_disk_gb=int(fields["container_disk_gb"]),  # type: ignore[call-overload]
        metadata={},
    )


def _is_supplied(value: object) -> bool:
    return isinstance(value, str) and bool(value) and not value.startswith("<")


def _refusal() -> str:
    return "\n".join(
        [
            "# Boot B run -- REFUSED, no request rendered",
            "",
            "`config/spend.toml` is in state `unconfigured`. Nothing below it can be",
            "derived, so this is a refusal rather than a request with blanks in it.",
            "The ceilings and the card are Tyrel's (CLAUDE.md hard rule 1).",
            "",
            "No pod, lease, preview or provider call results from this refusal.",
            "",
        ]
    )


def _render(
    policy: SpendPolicy,
    card: CardProfile,
    lifetime: int,
    pod_cost: Decimal,
    obstacles: list[str],
    request: dict[str, object],
) -> str:
    minutes = Decimal(lifetime) / Decimal(60)
    lines = [
        "# Boot B -- the real run, request for authorization",
        "",
        "This text authorizes nothing. It is derived from the sealed spend policy and",
        "the reviewed placement table so that what you read is what the launch will",
        "enforce. Permission is given, or refused, in the session the run happens in,",
        "for this exact action (GOVERNANCE 8; CLAUDE.md hard rules 1 and 2), and",
        "**separately from Boot A**.",
        "",
        "## What the run does",
        "",
        f"1. Creates one on-demand pod on **{card.name}** (`{card.gpu_type_id}`,",
        f"   {card.vram_gib} GiB, ${card.hourly_usd}/h from the reviewed price sheet), with",
        "   the network volume attached at creation and an explicit container disk.",
        f"2. Seals a hard lifetime of **{lifetime} seconds** (about {minutes:.0f} minutes):",
        "   the laptop supervisor and the pod-side dead-man timer each enforce it",
        "   independently, whichever fires first.",
        "3. Arms with **`ChannelControllerArmer`**, whose poll bound is set from the delay",
        "   Boot A measured. Boot A is a precondition, not a suggestion: without its",
        "   measurement the 300-second bound is a guess.",
        "4. The pod's primary process is the provider-neutral timer, whose mandatory",
        "   bootstrap is **`pod_run`**: the full journaled bootstrap (repository,",
        "   configuration, uv environment, transfer, model store, chair cache,",
        "   preflight), then the orchestrator over the volume, then a hold to the",
        "   hard deadline.",
        "5. **TRANSFER sends nothing.** The submission is already on the volume; the",
        "   request names no transfer target and no bootstrap submission manifest, so",
        "   TRANSFER records `nothing-to-transfer` rather than re-uploading what the pod",
        "   is here to read.",
        "",
        "## Which roster this request names, and what changing it costs",
        "",
        "The bootstrap half names `config/models.toml`, the shipped **fixture** roster, and",
        "lets the serving catalogue default to `config/serving_recipes.toml` beside it. That",
        "is the only pair `bootstrap_main` will default: name any other roster and it refuses",
        "at plan time unless the catalogue is named with it, because a roster preflighted",
        "against the wrong catalogue serves chairs no preflight looked at. A real-roster run",
        "therefore edits three flags together -- `--models-config config/models-real.toml`,",
        "`--serving-recipes-config config/serving_recipes_real.toml`, and",
        "`--witness-context-config config/witness_context-real.toml` -- and needs a card that",
        "can actually serve every chair in it, which is a decision about this run's card and",
        "roster together rather than one this file can make.",
        "",
        "## What it needs to be green, and where each part can go red",
        "",
        "- The image must meet the image contract in `operations/pod/README.md`. The",
        "  bootstrap refuses by name, before `git fetch`, if the checkout, the origin",
        "  remote, the tools or the pre-built `.venv` are not where it says.",
        "- The container disk must actually hold the serving stack twice over. The",
        "  bootstrap measures free space before `uv sync` and refuses by name if it is",
        "  short, rather than failing with no space left part way through the download.",
        "- Every serving row the roster selects must be stamped proven. An unproven row",
        "  is refused by name at PREFLIGHT, which is red, which closes the pod.",
        "",
        "## Ceilings the launch will enforce",
        "",
        f"- `max_hourly_usd` = ${policy.max_hourly_usd} (pod plus attached volume)",
        f"- `max_estimated_metered_cost_usd` = ${policy.max_estimated_metered_cost_usd}",
        f"- `account_balance_floor_usd` = ${policy.account_balance_floor_usd}",
        f"- `hard_lifetime_seconds` = {policy.hard_lifetime_seconds}; this run requests",
        f"  {lifetime}",
        f"- `billing_cutoff_margin_seconds` = {policy.billing_cutoff_margin_seconds}",
        "",
        "## Cost",
        "",
        f"Pod: ${card.hourly_usd}/h x {lifetime}s = **about ${pod_cost}** for a full",
        "lifetime, plus the attached volume's ongoing hourly price, which is added at",
        "preview from the provider factory's price sheet and stated in the close report.",
        "",
    ]
    if obstacles:
        lines += ["## Why the preview will refuse as configured", ""]
        lines += [f"- {obstacle}" for obstacle in obstacles]
        lines += [""]
    lines += [
        "## What only Tyrel supplies",
        "",
        "- In-session permission for this exact run (Boot A's permission is not it).",
        "- The pinned image digest, the network volume id and the repository commit",
        "  below where they still read as not yet supplied.",
        "- The run id, which names this run's tree on the volume.",
        "- `hard_deadline` below, an RFC3339 UTC timestamp at least this run's own",
        "  lifetime past whenever it is authorized.",
        "- The pod-side timer's provider capability, inside the pod, by the route the",
        "  pre-Boot-A checklist settled. The exact variable is the one",
        "  `operations.pod.provider_runpod:timer_context_from_environment` -- the timer",
        "  factory this request already names -- requires; without it the pod cannot",
        "  close itself, and `metadata` is refused as a route because the field is",
        "  credential-shaped. See the checklist row in operations/pod/README.md.",
        "- The S3 access and secret keys in the launching shell, for the report channel.",
        "- The untracked provider and controller-armer factories the command names.",
        "",
        "## The command",
        "",
        "```",
        "python -m operations.pod.cli \\",
        "  --provider-factory <untracked module:callable returning RunPodProvider> \\",
        "  --controller-armer-factory <untracked module:callable returning ChannelControllerArmer> \\",
        "  --spend config/spend.toml --leases <lease root for this account> \\",
        "  --provider-name runpod --notify \\",
        "  --record-fixture workbench/raw/boot-b-fixture.jsonl \\",
        "  create --request <path to the JSON below>",
        "```",
        "",
        "## The pod request",
        "",
        "```json",
        json.dumps(request, indent=2, sort_keys=True),
        "```",
        "",
    ]
    return "\n".join(lines)


def _cents(value: Decimal) -> Decimal:
    return value.quantize(Decimal("0.01"), rounding=ROUND_UP)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Render the Boot B run request from the sealed spend policy",
        allow_abbrev=False,
    )
    parser.add_argument("--spend", type=Path, default=Path("config/spend.toml"))
    parser.add_argument("--placement", type=Path, default=Path("config/pod_placement.toml"))
    parser.add_argument("--image")
    parser.add_argument("--volume-id")
    parser.add_argument("--repository-commit")
    parser.add_argument("--run-id")
    parser.add_argument(
        "--gpu-type",
        help="reviewed gpu_type_id to run on; omit for the cheapest reviewed card",
    )
    parser.add_argument(
        "--hard-deadline",
        help="RFC3339 UTC timestamp; omit to leave it a fill-in-by-hand placeholder",
    )
    args = parser.parse_args(argv)
    try:
        rendered = render_boot_b_request(
            load_spend_policy(args.spend),
            load_placement_table(args.placement),
            image=args.image,
            volume_id=args.volume_id,
            repository_commit=args.repository_commit,
            run_id=args.run_id,
            gpu_type=args.gpu_type,
            hard_deadline=args.hard_deadline,
        )
    except (ValueError, SpendRefusal) as error:
        print(f"# Boot B run -- REFUSED\n\n{error}\n", end="")
        return 2
    print(rendered.text, end="")
    return 2 if rendered.refused else 0


if __name__ == "__main__":  # pragma: no cover - command wrapper
    raise SystemExit(main())
